// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module log_28_15_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        x_V,
        ap_return
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [26:0] x_V;
output  [27:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_idle_pp0;
reg    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
reg    ap_block_pp0_stage0_11001;
wire   [5:0] log_apfixed_reduce_3_address0;
reg    log_apfixed_reduce_3_ce0;
wire   [5:0] log_apfixed_reduce_3_q0;
wire   [5:0] log_apfixed_reduce_2_address0;
reg    log_apfixed_reduce_2_ce0;
wire   [21:0] log_apfixed_reduce_2_q0;
wire   [3:0] log_apfixed_reduce_s_address0;
reg    log_apfixed_reduce_s_ce0;
wire   [17:0] log_apfixed_reduce_s_q0;
reg   [34:0] p_Val2_54_lcssa_reg_357;
reg   [34:0] p_Val2_54_lcssa_reg_357_pp0_iter2_reg;
wire   [0:0] icmp_ln1497_fu_554_p2;
reg   [0:0] icmp_ln1497_reg_2214;
reg   [0:0] icmp_ln1497_reg_2214_pp0_iter1_reg;
reg   [0:0] icmp_ln1497_reg_2214_pp0_iter2_reg;
reg   [0:0] icmp_ln1497_reg_2214_pp0_iter3_reg;
reg   [0:0] icmp_ln1497_reg_2214_pp0_iter4_reg;
reg   [0:0] icmp_ln1497_reg_2214_pp0_iter5_reg;
wire   [34:0] p_Result_6_fu_560_p4;
wire   [34:0] shl_ln_fu_598_p3;
wire   [0:0] and_ln730_fu_586_p2;
wire   [34:0] shl_ln1299_1_fu_648_p3;
wire   [0:0] or_ln730_fu_638_p2;
wire   [34:0] shl_ln1299_2_fu_698_p3;
wire   [0:0] or_ln730_1_fu_688_p2;
wire   [34:0] shl_ln1299_3_fu_748_p3;
wire   [0:0] or_ln730_2_fu_738_p2;
wire   [34:0] shl_ln1299_4_fu_798_p3;
wire   [0:0] or_ln730_3_fu_788_p2;
wire   [34:0] shl_ln1299_5_fu_848_p3;
wire   [0:0] or_ln730_4_fu_838_p2;
wire   [34:0] shl_ln1299_6_fu_898_p3;
wire   [0:0] or_ln730_5_fu_888_p2;
wire   [34:0] shl_ln1299_7_fu_948_p3;
wire   [0:0] or_ln730_6_fu_938_p2;
wire   [34:0] shl_ln1299_8_fu_998_p3;
wire   [0:0] or_ln730_7_fu_988_p2;
wire   [34:0] shl_ln1299_9_fu_1048_p3;
wire   [0:0] or_ln730_8_fu_1038_p2;
wire   [34:0] shl_ln1299_s_fu_1098_p3;
wire   [0:0] or_ln730_9_fu_1088_p2;
wire   [34:0] shl_ln1299_10_fu_1148_p3;
wire   [0:0] or_ln730_10_fu_1138_p2;
wire   [34:0] shl_ln1299_11_fu_1198_p3;
wire   [0:0] or_ln730_11_fu_1188_p2;
wire   [34:0] shl_ln1299_12_fu_1248_p3;
wire   [0:0] or_ln730_12_fu_1238_p2;
wire   [34:0] shl_ln1299_13_fu_1298_p3;
wire   [0:0] or_ln730_13_fu_1288_p2;
wire   [34:0] shl_ln1299_14_fu_1348_p3;
wire   [0:0] or_ln730_14_fu_1338_p2;
wire   [34:0] shl_ln1299_15_fu_1398_p3;
wire   [0:0] or_ln730_15_fu_1388_p2;
wire   [34:0] shl_ln1299_16_fu_1448_p3;
wire   [0:0] or_ln730_16_fu_1438_p2;
wire   [34:0] shl_ln1299_17_fu_1498_p3;
wire   [0:0] or_ln730_17_fu_1488_p2;
wire   [34:0] shl_ln1299_18_fu_1548_p3;
wire   [0:0] or_ln730_18_fu_1538_p2;
wire   [34:0] shl_ln1299_19_fu_1598_p3;
wire   [0:0] or_ln730_19_fu_1588_p2;
wire   [34:0] shl_ln1299_20_fu_1648_p3;
wire   [0:0] or_ln730_20_fu_1638_p2;
wire   [34:0] shl_ln1299_21_fu_1698_p3;
wire   [0:0] or_ln730_21_fu_1688_p2;
wire   [34:0] shl_ln1299_22_fu_1748_p3;
wire   [0:0] or_ln730_22_fu_1738_p2;
wire   [34:0] shl_ln1299_23_fu_1798_p3;
wire   [0:0] or_ln730_23_fu_1788_p2;
wire   [34:0] shl_ln1299_24_fu_1844_p3;
wire   [0:0] or_ln730_24_fu_1834_p2;
wire   [4:0] select_ln730_fu_1864_p3;
wire   [0:0] and_ln730_76_fu_1858_p2;
wire   [34:0] select_ln730_1_fu_1880_p3;
reg   [5:0] b_frac_tilde_inverse_reg_2457;
reg   [21:0] log_sum_V_reg_2462;
reg   [21:0] log_sum_V_reg_2462_pp0_iter3_reg;
reg   [21:0] log_sum_V_reg_2462_pp0_iter4_reg;
wire   [40:0] r_V_8_fu_1931_p2;
reg   [40:0] r_V_8_reg_2467;
reg   [23:0] z1_V_reg_2474;
reg   [3:0] a_V_reg_2480;
reg   [14:0] tmp_33_reg_2491;
reg   [8:0] trunc_ln_reg_2496;
reg   [15:0] trunc_ln708_s_reg_2501;
reg   [21:0] tmp_34_reg_2506;
wire   [21:0] add_ln703_22_fu_2129_p2;
reg   [21:0] add_ln703_22_reg_2511;
reg    ap_block_pp0_stage0_subdone;
wire   [34:0] ap_phi_reg_pp0_iter0_p_Val2_54_lcssa_reg_357;
reg   [34:0] ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357;
reg   [5:0] ap_phi_mux_index0_V_phi_fu_422_p4;
wire   [5:0] ap_phi_reg_pp0_iter1_index0_V_reg_419;
wire   [0:0] p_Result_s_fu_1888_p3;
wire   [4:0] ap_phi_reg_pp0_iter0_t_V_lcssa_reg_428;
reg   [4:0] ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428;
reg   [4:0] ap_phi_reg_pp0_iter2_t_V_lcssa_reg_428;
reg   [4:0] ap_phi_reg_pp0_iter3_t_V_lcssa_reg_428;
reg   [4:0] ap_phi_reg_pp0_iter4_t_V_lcssa_reg_428;
reg   [4:0] ap_phi_reg_pp0_iter5_t_V_lcssa_reg_428;
reg   [27:0] ap_phi_mux_agg_result_V_0_phi_fu_547_p4;
wire  signed [27:0] r_V_6_fu_2199_p1;
reg   [27:0] ap_phi_reg_pp0_iter6_agg_result_V_0_reg_543;
wire   [27:0] ap_phi_reg_pp0_iter0_agg_result_V_0_reg_543;
reg   [27:0] ap_phi_reg_pp0_iter1_agg_result_V_0_reg_543;
reg   [27:0] ap_phi_reg_pp0_iter2_agg_result_V_0_reg_543;
reg   [27:0] ap_phi_reg_pp0_iter3_agg_result_V_0_reg_543;
reg   [27:0] ap_phi_reg_pp0_iter4_agg_result_V_0_reg_543;
reg   [27:0] ap_phi_reg_pp0_iter5_agg_result_V_0_reg_543;
wire   [63:0] zext_ln544_fu_1918_p1;
wire   [63:0] zext_ln544_1_fu_2033_p1;
wire   [0:0] tmp_fu_570_p3;
wire   [0:0] tmp_43_fu_578_p3;
wire   [0:0] xor_ln730_fu_592_p2;
wire   [0:0] and_ln730_1_fu_614_p2;
wire   [0:0] tmp_44_fu_606_p3;
wire   [0:0] xor_ln730_1_fu_626_p2;
wire   [0:0] and_ln730_2_fu_620_p2;
wire   [0:0] and_ln730_3_fu_632_p2;
wire   [25:0] trunc_ln1299_fu_644_p1;
wire   [0:0] and_ln730_4_fu_664_p2;
wire   [0:0] tmp_45_fu_656_p3;
wire   [0:0] xor_ln730_2_fu_676_p2;
wire   [0:0] and_ln730_5_fu_670_p2;
wire   [0:0] and_ln730_6_fu_682_p2;
wire   [24:0] trunc_ln1299_1_fu_694_p1;
wire   [0:0] and_ln730_7_fu_714_p2;
wire   [0:0] tmp_46_fu_706_p3;
wire   [0:0] xor_ln730_3_fu_726_p2;
wire   [0:0] and_ln730_8_fu_720_p2;
wire   [0:0] and_ln730_9_fu_732_p2;
wire   [23:0] trunc_ln1299_2_fu_744_p1;
wire   [0:0] and_ln730_10_fu_764_p2;
wire   [0:0] tmp_47_fu_756_p3;
wire   [0:0] xor_ln730_4_fu_776_p2;
wire   [0:0] and_ln730_11_fu_770_p2;
wire   [0:0] and_ln730_12_fu_782_p2;
wire   [22:0] trunc_ln1299_3_fu_794_p1;
wire   [0:0] and_ln730_13_fu_814_p2;
wire   [0:0] tmp_48_fu_806_p3;
wire   [0:0] xor_ln730_5_fu_826_p2;
wire   [0:0] and_ln730_14_fu_820_p2;
wire   [0:0] and_ln730_15_fu_832_p2;
wire   [21:0] trunc_ln1299_4_fu_844_p1;
wire   [0:0] and_ln730_16_fu_864_p2;
wire   [0:0] tmp_49_fu_856_p3;
wire   [0:0] xor_ln730_6_fu_876_p2;
wire   [0:0] and_ln730_17_fu_870_p2;
wire   [0:0] and_ln730_18_fu_882_p2;
wire   [20:0] trunc_ln1299_5_fu_894_p1;
wire   [0:0] and_ln730_19_fu_914_p2;
wire   [0:0] tmp_50_fu_906_p3;
wire   [0:0] xor_ln730_7_fu_926_p2;
wire   [0:0] and_ln730_20_fu_920_p2;
wire   [0:0] and_ln730_21_fu_932_p2;
wire   [19:0] trunc_ln1299_6_fu_944_p1;
wire   [0:0] and_ln730_22_fu_964_p2;
wire   [0:0] tmp_51_fu_956_p3;
wire   [0:0] xor_ln730_8_fu_976_p2;
wire   [0:0] and_ln730_23_fu_970_p2;
wire   [0:0] and_ln730_24_fu_982_p2;
wire   [18:0] trunc_ln1299_7_fu_994_p1;
wire   [0:0] and_ln730_25_fu_1014_p2;
wire   [0:0] tmp_52_fu_1006_p3;
wire   [0:0] xor_ln730_9_fu_1026_p2;
wire   [0:0] and_ln730_26_fu_1020_p2;
wire   [0:0] and_ln730_27_fu_1032_p2;
wire   [17:0] trunc_ln1299_8_fu_1044_p1;
wire   [0:0] and_ln730_28_fu_1064_p2;
wire   [0:0] tmp_53_fu_1056_p3;
wire   [0:0] xor_ln730_10_fu_1076_p2;
wire   [0:0] and_ln730_29_fu_1070_p2;
wire   [0:0] and_ln730_30_fu_1082_p2;
wire   [16:0] trunc_ln1299_9_fu_1094_p1;
wire   [0:0] and_ln730_31_fu_1114_p2;
wire   [0:0] tmp_54_fu_1106_p3;
wire   [0:0] xor_ln730_11_fu_1126_p2;
wire   [0:0] and_ln730_32_fu_1120_p2;
wire   [0:0] and_ln730_33_fu_1132_p2;
wire   [15:0] trunc_ln1299_10_fu_1144_p1;
wire   [0:0] and_ln730_34_fu_1164_p2;
wire   [0:0] tmp_55_fu_1156_p3;
wire   [0:0] xor_ln730_12_fu_1176_p2;
wire   [0:0] and_ln730_35_fu_1170_p2;
wire   [0:0] and_ln730_36_fu_1182_p2;
wire   [14:0] trunc_ln1299_11_fu_1194_p1;
wire   [0:0] and_ln730_37_fu_1214_p2;
wire   [0:0] tmp_56_fu_1206_p3;
wire   [0:0] xor_ln730_13_fu_1226_p2;
wire   [0:0] and_ln730_38_fu_1220_p2;
wire   [0:0] and_ln730_39_fu_1232_p2;
wire   [13:0] trunc_ln1299_12_fu_1244_p1;
wire   [0:0] and_ln730_40_fu_1264_p2;
wire   [0:0] tmp_57_fu_1256_p3;
wire   [0:0] xor_ln730_14_fu_1276_p2;
wire   [0:0] and_ln730_41_fu_1270_p2;
wire   [0:0] and_ln730_42_fu_1282_p2;
wire   [12:0] trunc_ln1299_13_fu_1294_p1;
wire   [0:0] and_ln730_43_fu_1314_p2;
wire   [0:0] tmp_63_fu_1306_p3;
wire   [0:0] xor_ln730_15_fu_1326_p2;
wire   [0:0] and_ln730_44_fu_1320_p2;
wire   [0:0] and_ln730_45_fu_1332_p2;
wire   [11:0] trunc_ln1299_14_fu_1344_p1;
wire   [0:0] and_ln730_46_fu_1364_p2;
wire   [0:0] tmp_64_fu_1356_p3;
wire   [0:0] xor_ln730_16_fu_1376_p2;
wire   [0:0] and_ln730_47_fu_1370_p2;
wire   [0:0] and_ln730_48_fu_1382_p2;
wire   [10:0] trunc_ln1299_15_fu_1394_p1;
wire   [0:0] and_ln730_49_fu_1414_p2;
wire   [0:0] tmp_65_fu_1406_p3;
wire   [0:0] xor_ln730_17_fu_1426_p2;
wire   [0:0] and_ln730_50_fu_1420_p2;
wire   [0:0] and_ln730_51_fu_1432_p2;
wire   [9:0] trunc_ln1299_16_fu_1444_p1;
wire   [0:0] and_ln730_52_fu_1464_p2;
wire   [0:0] tmp_66_fu_1456_p3;
wire   [0:0] xor_ln730_18_fu_1476_p2;
wire   [0:0] and_ln730_53_fu_1470_p2;
wire   [0:0] and_ln730_54_fu_1482_p2;
wire   [8:0] trunc_ln1299_17_fu_1494_p1;
wire   [0:0] and_ln730_55_fu_1514_p2;
wire   [0:0] tmp_67_fu_1506_p3;
wire   [0:0] xor_ln730_19_fu_1526_p2;
wire   [0:0] and_ln730_56_fu_1520_p2;
wire   [0:0] and_ln730_57_fu_1532_p2;
wire   [7:0] trunc_ln1299_18_fu_1544_p1;
wire   [0:0] and_ln730_58_fu_1564_p2;
wire   [0:0] tmp_68_fu_1556_p3;
wire   [0:0] xor_ln730_20_fu_1576_p2;
wire   [0:0] and_ln730_59_fu_1570_p2;
wire   [0:0] and_ln730_60_fu_1582_p2;
wire   [6:0] trunc_ln1299_19_fu_1594_p1;
wire   [0:0] and_ln730_61_fu_1614_p2;
wire   [0:0] tmp_69_fu_1606_p3;
wire   [0:0] xor_ln730_21_fu_1626_p2;
wire   [0:0] and_ln730_62_fu_1620_p2;
wire   [0:0] and_ln730_63_fu_1632_p2;
wire   [5:0] trunc_ln1299_20_fu_1644_p1;
wire   [0:0] and_ln730_64_fu_1664_p2;
wire   [0:0] tmp_70_fu_1656_p3;
wire   [0:0] xor_ln730_22_fu_1676_p2;
wire   [0:0] and_ln730_65_fu_1670_p2;
wire   [0:0] and_ln730_66_fu_1682_p2;
wire   [4:0] trunc_ln1299_21_fu_1694_p1;
wire   [0:0] and_ln730_67_fu_1714_p2;
wire   [0:0] tmp_71_fu_1706_p3;
wire   [0:0] xor_ln730_23_fu_1726_p2;
wire   [0:0] and_ln730_68_fu_1720_p2;
wire   [0:0] and_ln730_69_fu_1732_p2;
wire   [3:0] trunc_ln1299_22_fu_1744_p1;
wire   [0:0] and_ln730_70_fu_1764_p2;
wire   [0:0] tmp_72_fu_1756_p3;
wire   [0:0] xor_ln730_24_fu_1776_p2;
wire   [0:0] and_ln730_71_fu_1770_p2;
wire   [0:0] and_ln730_72_fu_1782_p2;
wire   [2:0] trunc_ln1299_23_fu_1794_p1;
wire   [0:0] and_ln730_73_fu_1810_p2;
wire   [0:0] trunc_ln730_fu_1806_p1;
wire   [0:0] xor_ln730_25_fu_1822_p2;
wire   [0:0] and_ln730_74_fu_1816_p2;
wire   [0:0] and_ln730_75_fu_1828_p2;
wire   [1:0] trunc_ln1299_24_fu_1840_p1;
wire   [0:0] xor_ln730_26_fu_1852_p2;
wire   [34:0] st_fu_1872_p3;
wire   [34:0] r_V_8_fu_1931_p0;
wire   [5:0] r_V_8_fu_1931_p1;
wire   [22:0] tmp_s_fu_1964_p4;
wire   [27:0] sf_fu_1973_p3;
wire   [0:0] tmp_74_fu_1957_p3;
wire   [28:0] tmp_31_fu_1981_p3;
wire   [28:0] zext_ln1333_fu_1988_p1;
wire   [19:0] tmp_32_fu_2000_p4;
wire   [27:0] lhs_V_fu_2009_p3;
wire   [28:0] zext_ln703_fu_2017_p1;
wire   [28:0] eZ_V_fu_1992_p3;
wire   [28:0] grp_fu_2204_p3;
wire  signed [4:0] r_V_7_fu_2059_p0;
wire   [8:0] r_V_10_fu_2072_p0;
wire   [17:0] zext_ln1116_fu_2069_p1;
wire   [8:0] r_V_10_fu_2072_p1;
wire   [17:0] r_V_10_fu_2072_p2;
wire   [24:0] lhs_V_1_fu_2088_p3;
wire   [16:0] r_V_s_fu_2078_p4;
wire   [25:0] zext_ln728_fu_2095_p1;
wire   [25:0] zext_ln703_2_fu_2099_p1;
wire   [25:0] ret_V_1_fu_2103_p2;
wire   [27:0] r_V_7_fu_2059_p2;
wire   [21:0] zext_ln203_fu_2065_p1;
wire   [27:0] shl_ln1_fu_2137_p3;
wire  signed [28:0] sext_ln703_fu_2144_p1;
wire  signed [28:0] sum_V_fu_2134_p1;
wire   [28:0] add_ln703_23_fu_2151_p2;
wire  signed [28:0] sext_ln703_1_fu_2148_p1;
wire   [28:0] log_base_V_fu_2157_p2;
wire   [0:0] p_Result_7_fu_2163_p3;
wire   [9:0] shl_ln703_1_fu_2171_p3;
wire  signed [28:0] sext_ln703_2_fu_2179_p1;
wire   [28:0] log_base_V_1_fu_2183_p2;
wire   [19:0] trunc_ln708_23_fu_2189_p4;
wire   [23:0] grp_fu_2204_p0;
wire   [3:0] grp_fu_2204_p1;
wire   [28:0] grp_fu_2204_p2;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to5;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire   [27:0] grp_fu_2204_p00;
wire   [27:0] grp_fu_2204_p10;
wire   [40:0] r_V_8_fu_1931_p00;
wire   [40:0] r_V_8_fu_1931_p10;
reg    ap_condition_479;
reg    ap_condition_63;
reg    ap_condition_326;
reg    ap_condition_329;
reg    ap_condition_332;
reg    ap_condition_335;
reg    ap_condition_338;
reg    ap_condition_341;
reg    ap_condition_344;
reg    ap_condition_347;
reg    ap_condition_350;
reg    ap_condition_353;
reg    ap_condition_356;
reg    ap_condition_359;
reg    ap_condition_362;
reg    ap_condition_365;
reg    ap_condition_368;
reg    ap_condition_371;
reg    ap_condition_374;
reg    ap_condition_377;
reg    ap_condition_380;
reg    ap_condition_383;
reg    ap_condition_386;
reg    ap_condition_389;
reg    ap_condition_392;
reg    ap_condition_395;
reg    ap_condition_398;
reg    ap_condition_401;
reg    ap_condition_270;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
end

log_28_15_s_log_abkb #(
    .DataWidth( 6 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_3_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_3_address0),
    .ce0(log_apfixed_reduce_3_ce0),
    .q0(log_apfixed_reduce_3_q0)
);

log_28_15_s_log_acud #(
    .DataWidth( 22 ),
    .AddressRange( 64 ),
    .AddressWidth( 6 ))
log_apfixed_reduce_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_2_address0),
    .ce0(log_apfixed_reduce_2_ce0),
    .q0(log_apfixed_reduce_2_q0)
);

log_28_15_s_log_adEe #(
    .DataWidth( 18 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
log_apfixed_reduce_s_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(log_apfixed_reduce_s_address0),
    .ce0(log_apfixed_reduce_s_ce0),
    .q0(log_apfixed_reduce_s_q0)
);

mabonsoc_mac_mulseOg #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 4 ),
    .din2_WIDTH( 29 ),
    .dout_WIDTH( 29 ))
mabonsoc_mac_mulseOg_U1(
    .din0(grp_fu_2204_p0),
    .din1(grp_fu_2204_p1),
    .din2(grp_fu_2204_p2),
    .dout(grp_fu_2204_p3)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_63)) begin
        if ((icmp_ln1497_fu_554_p2 == 1'd1)) begin
            ap_phi_reg_pp0_iter1_agg_result_V_0_reg_543 <= 28'd134217728;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter0_agg_result_V_0_reg_543;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_63)) begin
        if ((1'b1 == ap_condition_270)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= select_ln730_1_fu_1880_p3;
        end else if ((1'b1 == ap_condition_401)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_24_fu_1844_p3;
        end else if ((1'b1 == ap_condition_398)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_23_fu_1798_p3;
        end else if ((1'b1 == ap_condition_395)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_22_fu_1748_p3;
        end else if ((1'b1 == ap_condition_392)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_21_fu_1698_p3;
        end else if ((1'b1 == ap_condition_389)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_20_fu_1648_p3;
        end else if ((1'b1 == ap_condition_386)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_19_fu_1598_p3;
        end else if ((1'b1 == ap_condition_383)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_18_fu_1548_p3;
        end else if ((1'b1 == ap_condition_380)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_17_fu_1498_p3;
        end else if ((1'b1 == ap_condition_377)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_16_fu_1448_p3;
        end else if ((1'b1 == ap_condition_374)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_15_fu_1398_p3;
        end else if ((1'b1 == ap_condition_371)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_14_fu_1348_p3;
        end else if ((1'b1 == ap_condition_368)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_13_fu_1298_p3;
        end else if ((1'b1 == ap_condition_365)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_12_fu_1248_p3;
        end else if ((1'b1 == ap_condition_362)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_11_fu_1198_p3;
        end else if ((1'b1 == ap_condition_359)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_10_fu_1148_p3;
        end else if ((1'b1 == ap_condition_356)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_s_fu_1098_p3;
        end else if ((1'b1 == ap_condition_353)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_9_fu_1048_p3;
        end else if ((1'b1 == ap_condition_350)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_8_fu_998_p3;
        end else if ((1'b1 == ap_condition_347)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_7_fu_948_p3;
        end else if ((1'b1 == ap_condition_344)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_6_fu_898_p3;
        end else if ((1'b1 == ap_condition_341)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_5_fu_848_p3;
        end else if ((1'b1 == ap_condition_338)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_4_fu_798_p3;
        end else if ((1'b1 == ap_condition_335)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_3_fu_748_p3;
        end else if ((1'b1 == ap_condition_332)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_2_fu_698_p3;
        end else if ((1'b1 == ap_condition_329)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln1299_1_fu_648_p3;
        end else if ((1'b1 == ap_condition_326)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= shl_ln_fu_598_p3;
        end else if (((icmp_ln1497_fu_554_p2 == 1'd0) & (1'd1 == and_ln730_fu_586_p2))) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= p_Result_6_fu_560_p4;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357 <= ap_phi_reg_pp0_iter0_p_Val2_54_lcssa_reg_357;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_63)) begin
        if ((1'b1 == ap_condition_270)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= select_ln730_fu_1864_p3;
        end else if ((1'b1 == ap_condition_401)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd20;
        end else if ((1'b1 == ap_condition_398)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd21;
        end else if ((1'b1 == ap_condition_395)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd22;
        end else if ((1'b1 == ap_condition_392)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd23;
        end else if ((1'b1 == ap_condition_389)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd24;
        end else if ((1'b1 == ap_condition_386)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd25;
        end else if ((1'b1 == ap_condition_383)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd26;
        end else if ((1'b1 == ap_condition_380)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd27;
        end else if ((1'b1 == ap_condition_377)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd28;
        end else if ((1'b1 == ap_condition_374)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd29;
        end else if ((1'b1 == ap_condition_371)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd30;
        end else if ((1'b1 == ap_condition_368)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd31;
        end else if ((1'b1 == ap_condition_365)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd0;
        end else if ((1'b1 == ap_condition_362)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd1;
        end else if ((1'b1 == ap_condition_359)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd2;
        end else if ((1'b1 == ap_condition_356)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd3;
        end else if ((1'b1 == ap_condition_353)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd4;
        end else if ((1'b1 == ap_condition_350)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd5;
        end else if ((1'b1 == ap_condition_347)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd6;
        end else if ((1'b1 == ap_condition_344)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd7;
        end else if ((1'b1 == ap_condition_341)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd8;
        end else if ((1'b1 == ap_condition_338)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd9;
        end else if ((1'b1 == ap_condition_335)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd10;
        end else if ((1'b1 == ap_condition_332)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd11;
        end else if ((1'b1 == ap_condition_329)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd12;
        end else if ((1'b1 == ap_condition_326)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd13;
        end else if (((icmp_ln1497_fu_554_p2 == 1'd0) & (1'd1 == and_ln730_fu_586_p2))) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= 5'd14;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428 <= ap_phi_reg_pp0_iter0_t_V_lcssa_reg_428;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1497_reg_2214_pp0_iter2_reg == 1'd0))) begin
        a_V_reg_2480 <= {{r_V_8_fu_1931_p2[34:31]}};
        r_V_8_reg_2467 <= r_V_8_fu_1931_p2;
        z1_V_reg_2474 <= {{r_V_8_fu_1931_p2[34:11]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1497_reg_2214_pp0_iter4_reg == 1'd0))) begin
        add_ln703_22_reg_2511 <= add_ln703_22_fu_2129_p2;
        tmp_34_reg_2506 <= {{r_V_7_fu_2059_p2[27:6]}};
        trunc_ln708_s_reg_2501 <= {{ret_V_1_fu_2103_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_reg_pp0_iter2_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter1_agg_result_V_0_reg_543;
        ap_phi_reg_pp0_iter2_t_V_lcssa_reg_428 <= ap_phi_reg_pp0_iter1_t_V_lcssa_reg_428;
        p_Val2_54_lcssa_reg_357 <= ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter2 == 1'b1))) begin
        ap_phi_reg_pp0_iter3_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter2_agg_result_V_0_reg_543;
        ap_phi_reg_pp0_iter3_t_V_lcssa_reg_428 <= ap_phi_reg_pp0_iter2_t_V_lcssa_reg_428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter3 == 1'b1))) begin
        ap_phi_reg_pp0_iter4_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter3_agg_result_V_0_reg_543;
        ap_phi_reg_pp0_iter4_t_V_lcssa_reg_428 <= ap_phi_reg_pp0_iter3_t_V_lcssa_reg_428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        ap_phi_reg_pp0_iter5_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter4_agg_result_V_0_reg_543;
        ap_phi_reg_pp0_iter5_t_V_lcssa_reg_428 <= ap_phi_reg_pp0_iter4_t_V_lcssa_reg_428;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter5 == 1'b1))) begin
        ap_phi_reg_pp0_iter6_agg_result_V_0_reg_543 <= ap_phi_reg_pp0_iter5_agg_result_V_0_reg_543;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1497_reg_2214_pp0_iter1_reg == 1'd0))) begin
        b_frac_tilde_inverse_reg_2457 <= log_apfixed_reduce_3_q0;
        log_sum_V_reg_2462 <= log_apfixed_reduce_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln1497_reg_2214 <= icmp_ln1497_fu_554_p2;
        icmp_ln1497_reg_2214_pp0_iter1_reg <= icmp_ln1497_reg_2214;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        icmp_ln1497_reg_2214_pp0_iter2_reg <= icmp_ln1497_reg_2214_pp0_iter1_reg;
        icmp_ln1497_reg_2214_pp0_iter3_reg <= icmp_ln1497_reg_2214_pp0_iter2_reg;
        icmp_ln1497_reg_2214_pp0_iter4_reg <= icmp_ln1497_reg_2214_pp0_iter3_reg;
        icmp_ln1497_reg_2214_pp0_iter5_reg <= icmp_ln1497_reg_2214_pp0_iter4_reg;
        log_sum_V_reg_2462_pp0_iter3_reg <= log_sum_V_reg_2462;
        log_sum_V_reg_2462_pp0_iter4_reg <= log_sum_V_reg_2462_pp0_iter3_reg;
        p_Val2_54_lcssa_reg_357_pp0_iter2_reg <= p_Val2_54_lcssa_reg_357;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1497_reg_2214_pp0_iter3_reg == 1'd0))) begin
        tmp_33_reg_2491 <= {{grp_fu_2204_p3[28:14]}};
        trunc_ln_reg_2496 <= {{grp_fu_2204_p3[28:20]}};
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter6 == 1'b1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to5 = 1'b1;
    end else begin
        ap_idle_pp0_0to5 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter6 == 1'b1) & (icmp_ln1497_reg_2214_pp0_iter5_reg == 1'd0))) begin
        ap_phi_mux_agg_result_V_0_phi_fu_547_p4 = r_V_6_fu_2199_p1;
    end else begin
        ap_phi_mux_agg_result_V_0_phi_fu_547_p4 = ap_phi_reg_pp0_iter6_agg_result_V_0_reg_543;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_479)) begin
        if ((p_Result_s_fu_1888_p3 == 1'd0)) begin
            ap_phi_mux_index0_V_phi_fu_422_p4 = {{ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357[32:27]}};
        end else if ((p_Result_s_fu_1888_p3 == 1'd1)) begin
            ap_phi_mux_index0_V_phi_fu_422_p4 = {{ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357[33:28]}};
        end else begin
            ap_phi_mux_index0_V_phi_fu_422_p4 = ap_phi_reg_pp0_iter1_index0_V_reg_419;
        end
    end else begin
        ap_phi_mux_index0_V_phi_fu_422_p4 = ap_phi_reg_pp0_iter1_index0_V_reg_419;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to5 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        log_apfixed_reduce_2_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        log_apfixed_reduce_3_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter4 == 1'b1))) begin
        log_apfixed_reduce_s_ce0 = 1'b1;
    end else begin
        log_apfixed_reduce_s_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln703_22_fu_2129_p2 = (log_sum_V_reg_2462_pp0_iter4_reg + zext_ln203_fu_2065_p1);

assign add_ln703_23_fu_2151_p2 = ($signed(sext_ln703_fu_2144_p1) + $signed(sum_V_fu_2134_p1));

assign and_ln730_10_fu_764_p2 = (xor_ln730_3_fu_726_p2 & tmp_46_fu_706_p3);

assign and_ln730_11_fu_770_p2 = (tmp_47_fu_756_p3 & and_ln730_10_fu_764_p2);

assign and_ln730_12_fu_782_p2 = (xor_ln730_4_fu_776_p2 & tmp_45_fu_656_p3);

assign and_ln730_13_fu_814_p2 = (xor_ln730_4_fu_776_p2 & tmp_47_fu_756_p3);

assign and_ln730_14_fu_820_p2 = (tmp_48_fu_806_p3 & and_ln730_13_fu_814_p2);

assign and_ln730_15_fu_832_p2 = (xor_ln730_5_fu_826_p2 & tmp_46_fu_706_p3);

assign and_ln730_16_fu_864_p2 = (xor_ln730_5_fu_826_p2 & tmp_48_fu_806_p3);

assign and_ln730_17_fu_870_p2 = (tmp_49_fu_856_p3 & and_ln730_16_fu_864_p2);

assign and_ln730_18_fu_882_p2 = (xor_ln730_6_fu_876_p2 & tmp_47_fu_756_p3);

assign and_ln730_19_fu_914_p2 = (xor_ln730_6_fu_876_p2 & tmp_49_fu_856_p3);

assign and_ln730_1_fu_614_p2 = (xor_ln730_fu_592_p2 & tmp_43_fu_578_p3);

assign and_ln730_20_fu_920_p2 = (tmp_50_fu_906_p3 & and_ln730_19_fu_914_p2);

assign and_ln730_21_fu_932_p2 = (xor_ln730_7_fu_926_p2 & tmp_48_fu_806_p3);

assign and_ln730_22_fu_964_p2 = (xor_ln730_7_fu_926_p2 & tmp_50_fu_906_p3);

assign and_ln730_23_fu_970_p2 = (tmp_51_fu_956_p3 & and_ln730_22_fu_964_p2);

assign and_ln730_24_fu_982_p2 = (xor_ln730_8_fu_976_p2 & tmp_49_fu_856_p3);

assign and_ln730_25_fu_1014_p2 = (xor_ln730_8_fu_976_p2 & tmp_51_fu_956_p3);

assign and_ln730_26_fu_1020_p2 = (tmp_52_fu_1006_p3 & and_ln730_25_fu_1014_p2);

assign and_ln730_27_fu_1032_p2 = (xor_ln730_9_fu_1026_p2 & tmp_50_fu_906_p3);

assign and_ln730_28_fu_1064_p2 = (xor_ln730_9_fu_1026_p2 & tmp_52_fu_1006_p3);

assign and_ln730_29_fu_1070_p2 = (tmp_53_fu_1056_p3 & and_ln730_28_fu_1064_p2);

assign and_ln730_2_fu_620_p2 = (tmp_44_fu_606_p3 & and_ln730_1_fu_614_p2);

assign and_ln730_30_fu_1082_p2 = (xor_ln730_10_fu_1076_p2 & tmp_51_fu_956_p3);

assign and_ln730_31_fu_1114_p2 = (xor_ln730_10_fu_1076_p2 & tmp_53_fu_1056_p3);

assign and_ln730_32_fu_1120_p2 = (tmp_54_fu_1106_p3 & and_ln730_31_fu_1114_p2);

assign and_ln730_33_fu_1132_p2 = (xor_ln730_11_fu_1126_p2 & tmp_52_fu_1006_p3);

assign and_ln730_34_fu_1164_p2 = (xor_ln730_11_fu_1126_p2 & tmp_54_fu_1106_p3);

assign and_ln730_35_fu_1170_p2 = (tmp_55_fu_1156_p3 & and_ln730_34_fu_1164_p2);

assign and_ln730_36_fu_1182_p2 = (xor_ln730_12_fu_1176_p2 & tmp_53_fu_1056_p3);

assign and_ln730_37_fu_1214_p2 = (xor_ln730_12_fu_1176_p2 & tmp_55_fu_1156_p3);

assign and_ln730_38_fu_1220_p2 = (tmp_56_fu_1206_p3 & and_ln730_37_fu_1214_p2);

assign and_ln730_39_fu_1232_p2 = (xor_ln730_13_fu_1226_p2 & tmp_54_fu_1106_p3);

assign and_ln730_3_fu_632_p2 = (xor_ln730_1_fu_626_p2 & tmp_fu_570_p3);

assign and_ln730_40_fu_1264_p2 = (xor_ln730_13_fu_1226_p2 & tmp_56_fu_1206_p3);

assign and_ln730_41_fu_1270_p2 = (tmp_57_fu_1256_p3 & and_ln730_40_fu_1264_p2);

assign and_ln730_42_fu_1282_p2 = (xor_ln730_14_fu_1276_p2 & tmp_55_fu_1156_p3);

assign and_ln730_43_fu_1314_p2 = (xor_ln730_14_fu_1276_p2 & tmp_57_fu_1256_p3);

assign and_ln730_44_fu_1320_p2 = (tmp_63_fu_1306_p3 & and_ln730_43_fu_1314_p2);

assign and_ln730_45_fu_1332_p2 = (xor_ln730_15_fu_1326_p2 & tmp_56_fu_1206_p3);

assign and_ln730_46_fu_1364_p2 = (xor_ln730_15_fu_1326_p2 & tmp_63_fu_1306_p3);

assign and_ln730_47_fu_1370_p2 = (tmp_64_fu_1356_p3 & and_ln730_46_fu_1364_p2);

assign and_ln730_48_fu_1382_p2 = (xor_ln730_16_fu_1376_p2 & tmp_57_fu_1256_p3);

assign and_ln730_49_fu_1414_p2 = (xor_ln730_16_fu_1376_p2 & tmp_64_fu_1356_p3);

assign and_ln730_4_fu_664_p2 = (xor_ln730_1_fu_626_p2 & tmp_44_fu_606_p3);

assign and_ln730_50_fu_1420_p2 = (tmp_65_fu_1406_p3 & and_ln730_49_fu_1414_p2);

assign and_ln730_51_fu_1432_p2 = (xor_ln730_17_fu_1426_p2 & tmp_63_fu_1306_p3);

assign and_ln730_52_fu_1464_p2 = (xor_ln730_17_fu_1426_p2 & tmp_65_fu_1406_p3);

assign and_ln730_53_fu_1470_p2 = (tmp_66_fu_1456_p3 & and_ln730_52_fu_1464_p2);

assign and_ln730_54_fu_1482_p2 = (xor_ln730_18_fu_1476_p2 & tmp_64_fu_1356_p3);

assign and_ln730_55_fu_1514_p2 = (xor_ln730_18_fu_1476_p2 & tmp_66_fu_1456_p3);

assign and_ln730_56_fu_1520_p2 = (tmp_67_fu_1506_p3 & and_ln730_55_fu_1514_p2);

assign and_ln730_57_fu_1532_p2 = (xor_ln730_19_fu_1526_p2 & tmp_65_fu_1406_p3);

assign and_ln730_58_fu_1564_p2 = (xor_ln730_19_fu_1526_p2 & tmp_67_fu_1506_p3);

assign and_ln730_59_fu_1570_p2 = (tmp_68_fu_1556_p3 & and_ln730_58_fu_1564_p2);

assign and_ln730_5_fu_670_p2 = (tmp_45_fu_656_p3 & and_ln730_4_fu_664_p2);

assign and_ln730_60_fu_1582_p2 = (xor_ln730_20_fu_1576_p2 & tmp_66_fu_1456_p3);

assign and_ln730_61_fu_1614_p2 = (xor_ln730_20_fu_1576_p2 & tmp_68_fu_1556_p3);

assign and_ln730_62_fu_1620_p2 = (tmp_69_fu_1606_p3 & and_ln730_61_fu_1614_p2);

assign and_ln730_63_fu_1632_p2 = (xor_ln730_21_fu_1626_p2 & tmp_67_fu_1506_p3);

assign and_ln730_64_fu_1664_p2 = (xor_ln730_21_fu_1626_p2 & tmp_69_fu_1606_p3);

assign and_ln730_65_fu_1670_p2 = (tmp_70_fu_1656_p3 & and_ln730_64_fu_1664_p2);

assign and_ln730_66_fu_1682_p2 = (xor_ln730_22_fu_1676_p2 & tmp_68_fu_1556_p3);

assign and_ln730_67_fu_1714_p2 = (xor_ln730_22_fu_1676_p2 & tmp_70_fu_1656_p3);

assign and_ln730_68_fu_1720_p2 = (tmp_71_fu_1706_p3 & and_ln730_67_fu_1714_p2);

assign and_ln730_69_fu_1732_p2 = (xor_ln730_23_fu_1726_p2 & tmp_69_fu_1606_p3);

assign and_ln730_6_fu_682_p2 = (xor_ln730_2_fu_676_p2 & tmp_43_fu_578_p3);

assign and_ln730_70_fu_1764_p2 = (xor_ln730_23_fu_1726_p2 & tmp_71_fu_1706_p3);

assign and_ln730_71_fu_1770_p2 = (tmp_72_fu_1756_p3 & and_ln730_70_fu_1764_p2);

assign and_ln730_72_fu_1782_p2 = (xor_ln730_24_fu_1776_p2 & tmp_70_fu_1656_p3);

assign and_ln730_73_fu_1810_p2 = (xor_ln730_24_fu_1776_p2 & tmp_72_fu_1756_p3);

assign and_ln730_74_fu_1816_p2 = (trunc_ln730_fu_1806_p1 & and_ln730_73_fu_1810_p2);

assign and_ln730_75_fu_1828_p2 = (xor_ln730_25_fu_1822_p2 & tmp_71_fu_1706_p3);

assign and_ln730_76_fu_1858_p2 = (xor_ln730_26_fu_1852_p2 & tmp_72_fu_1756_p3);

assign and_ln730_7_fu_714_p2 = (xor_ln730_2_fu_676_p2 & tmp_45_fu_656_p3);

assign and_ln730_8_fu_720_p2 = (tmp_46_fu_706_p3 & and_ln730_7_fu_714_p2);

assign and_ln730_9_fu_732_p2 = (xor_ln730_3_fu_726_p2 & tmp_44_fu_606_p3);

assign and_ln730_fu_586_p2 = (tmp_fu_570_p3 & tmp_43_fu_578_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((ap_start == 1'b0) & (ap_start == 1'b1));
end

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start == 1'b0);
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_270 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (1'd0 == and_ln730_76_fu_1858_p2) & (or_ln730_24_fu_1834_p2 == 1'd0) & (or_ln730_23_fu_1788_p2 == 1'd0) & (or_ln730_22_fu_1738_p2 == 1'd0) & (or_ln730_21_fu_1688_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_326 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd1) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_329 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd1) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_332 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd1) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_335 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd1) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_338 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd1) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_341 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd1) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_344 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd1) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_347 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd1) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_350 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd1) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_353 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd1) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_356 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd1) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_359 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd1) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_362 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd1) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_365 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd1) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_368 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd1) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_371 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd1) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_374 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd1) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_377 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd1) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_380 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd1) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_383 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd1) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_386 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd1) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_389 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_21_fu_1688_p2 == 1'd1) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_392 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_22_fu_1738_p2 == 1'd1) & (or_ln730_21_fu_1688_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_395 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_23_fu_1788_p2 == 1'd1) & (or_ln730_22_fu_1738_p2 == 1'd0) & (or_ln730_21_fu_1688_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_398 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (or_ln730_24_fu_1834_p2 == 1'd1) & (or_ln730_23_fu_1788_p2 == 1'd0) & (or_ln730_22_fu_1738_p2 == 1'd0) & (or_ln730_21_fu_1688_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_401 = ((icmp_ln1497_fu_554_p2 == 1'd0) & (1'd1 == and_ln730_76_fu_1858_p2) & (or_ln730_24_fu_1834_p2 == 1'd0) & (or_ln730_23_fu_1788_p2 == 1'd0) & (or_ln730_22_fu_1738_p2 == 1'd0) & (or_ln730_21_fu_1688_p2 == 1'd0) & (or_ln730_20_fu_1638_p2 == 1'd0) & (or_ln730_19_fu_1588_p2 == 1'd0) & (or_ln730_18_fu_1538_p2 == 1'd0) & (or_ln730_17_fu_1488_p2 == 1'd0) & (or_ln730_16_fu_1438_p2 == 1'd0) & (or_ln730_15_fu_1388_p2 == 1'd0) & (or_ln730_14_fu_1338_p2 == 1'd0) & (or_ln730_13_fu_1288_p2 == 1'd0) & (or_ln730_12_fu_1238_p2 == 1'd0) & (or_ln730_11_fu_1188_p2 == 1'd0) & (or_ln730_10_fu_1138_p2 == 1'd0) & (or_ln730_9_fu_1088_p2 == 1'd0) & (or_ln730_8_fu_1038_p2 == 1'd0) & (or_ln730_7_fu_988_p2 == 1'd0) & (or_ln730_6_fu_938_p2 == 1'd0) & (or_ln730_5_fu_888_p2 == 1'd0) & (or_ln730_4_fu_838_p2 == 1'd0) & (or_ln730_3_fu_788_p2 == 1'd0) & (or_ln730_2_fu_738_p2 == 1'd0) & (or_ln730_1_fu_688_p2 == 1'd0) & (or_ln730_fu_638_p2 == 1'd0) & (1'd0 == and_ln730_fu_586_p2));
end

always @ (*) begin
    ap_condition_479 = ((icmp_ln1497_reg_2214 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

always @ (*) begin
    ap_condition_63 = ((1'b0 == ap_block_pp0_stage0_11001) & (ap_start == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0));
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_phi_reg_pp0_iter0_agg_result_V_0_reg_543 = 'bx;

assign ap_phi_reg_pp0_iter0_p_Val2_54_lcssa_reg_357 = 'bx;

assign ap_phi_reg_pp0_iter0_t_V_lcssa_reg_428 = 'bx;

assign ap_phi_reg_pp0_iter1_index0_V_reg_419 = 'bx;

assign ap_return = ap_phi_mux_agg_result_V_0_phi_fu_547_p4;

assign eZ_V_fu_1992_p3 = ((tmp_74_fu_1957_p3[0:0] === 1'b1) ? tmp_31_fu_1981_p3 : zext_ln1333_fu_1988_p1);

assign grp_fu_2204_p0 = grp_fu_2204_p00;

assign grp_fu_2204_p00 = z1_V_reg_2474;

assign grp_fu_2204_p1 = grp_fu_2204_p10;

assign grp_fu_2204_p10 = a_V_reg_2480;

assign grp_fu_2204_p2 = (zext_ln703_fu_2017_p1 + eZ_V_fu_1992_p3);

assign icmp_ln1497_fu_554_p2 = ((x_V == 27'd0) ? 1'b1 : 1'b0);

assign lhs_V_1_fu_2088_p3 = {{tmp_33_reg_2491}, {10'd0}};

assign lhs_V_fu_2009_p3 = {{tmp_32_fu_2000_p4}, {8'd0}};

assign log_apfixed_reduce_2_address0 = zext_ln544_fu_1918_p1;

assign log_apfixed_reduce_3_address0 = zext_ln544_fu_1918_p1;

assign log_apfixed_reduce_s_address0 = zext_ln544_1_fu_2033_p1;

assign log_base_V_1_fu_2183_p2 = ($signed(sext_ln703_2_fu_2179_p1) + $signed(log_base_V_fu_2157_p2));

assign log_base_V_fu_2157_p2 = ($signed(add_ln703_23_fu_2151_p2) + $signed(sext_ln703_1_fu_2148_p1));

assign or_ln730_10_fu_1138_p2 = (and_ln730_33_fu_1132_p2 | and_ln730_32_fu_1120_p2);

assign or_ln730_11_fu_1188_p2 = (and_ln730_36_fu_1182_p2 | and_ln730_35_fu_1170_p2);

assign or_ln730_12_fu_1238_p2 = (and_ln730_39_fu_1232_p2 | and_ln730_38_fu_1220_p2);

assign or_ln730_13_fu_1288_p2 = (and_ln730_42_fu_1282_p2 | and_ln730_41_fu_1270_p2);

assign or_ln730_14_fu_1338_p2 = (and_ln730_45_fu_1332_p2 | and_ln730_44_fu_1320_p2);

assign or_ln730_15_fu_1388_p2 = (and_ln730_48_fu_1382_p2 | and_ln730_47_fu_1370_p2);

assign or_ln730_16_fu_1438_p2 = (and_ln730_51_fu_1432_p2 | and_ln730_50_fu_1420_p2);

assign or_ln730_17_fu_1488_p2 = (and_ln730_54_fu_1482_p2 | and_ln730_53_fu_1470_p2);

assign or_ln730_18_fu_1538_p2 = (and_ln730_57_fu_1532_p2 | and_ln730_56_fu_1520_p2);

assign or_ln730_19_fu_1588_p2 = (and_ln730_60_fu_1582_p2 | and_ln730_59_fu_1570_p2);

assign or_ln730_1_fu_688_p2 = (and_ln730_6_fu_682_p2 | and_ln730_5_fu_670_p2);

assign or_ln730_20_fu_1638_p2 = (and_ln730_63_fu_1632_p2 | and_ln730_62_fu_1620_p2);

assign or_ln730_21_fu_1688_p2 = (and_ln730_66_fu_1682_p2 | and_ln730_65_fu_1670_p2);

assign or_ln730_22_fu_1738_p2 = (and_ln730_69_fu_1732_p2 | and_ln730_68_fu_1720_p2);

assign or_ln730_23_fu_1788_p2 = (and_ln730_72_fu_1782_p2 | and_ln730_71_fu_1770_p2);

assign or_ln730_24_fu_1834_p2 = (and_ln730_75_fu_1828_p2 | and_ln730_74_fu_1816_p2);

assign or_ln730_2_fu_738_p2 = (and_ln730_9_fu_732_p2 | and_ln730_8_fu_720_p2);

assign or_ln730_3_fu_788_p2 = (and_ln730_12_fu_782_p2 | and_ln730_11_fu_770_p2);

assign or_ln730_4_fu_838_p2 = (and_ln730_15_fu_832_p2 | and_ln730_14_fu_820_p2);

assign or_ln730_5_fu_888_p2 = (and_ln730_18_fu_882_p2 | and_ln730_17_fu_870_p2);

assign or_ln730_6_fu_938_p2 = (and_ln730_21_fu_932_p2 | and_ln730_20_fu_920_p2);

assign or_ln730_7_fu_988_p2 = (and_ln730_24_fu_982_p2 | and_ln730_23_fu_970_p2);

assign or_ln730_8_fu_1038_p2 = (and_ln730_27_fu_1032_p2 | and_ln730_26_fu_1020_p2);

assign or_ln730_9_fu_1088_p2 = (and_ln730_30_fu_1082_p2 | and_ln730_29_fu_1070_p2);

assign or_ln730_fu_638_p2 = (and_ln730_3_fu_632_p2 | and_ln730_2_fu_620_p2);

assign p_Result_6_fu_560_p4 = {{{{1'd0}, {x_V}}}, {7'd0}};

assign p_Result_7_fu_2163_p3 = log_base_V_fu_2157_p2[32'd28];

assign p_Result_s_fu_1888_p3 = ap_phi_reg_pp0_iter1_p_Val2_54_lcssa_reg_357[32'd34];

assign r_V_10_fu_2072_p0 = zext_ln1116_fu_2069_p1;

assign r_V_10_fu_2072_p1 = zext_ln1116_fu_2069_p1;

assign r_V_10_fu_2072_p2 = (r_V_10_fu_2072_p0 * r_V_10_fu_2072_p1);

assign r_V_6_fu_2199_p1 = $signed(trunc_ln708_23_fu_2189_p4);

assign r_V_7_fu_2059_p0 = ap_phi_reg_pp0_iter5_t_V_lcssa_reg_428;

assign r_V_7_fu_2059_p2 = ($signed(r_V_7_fu_2059_p0) * $signed('h2C5C85));

assign r_V_8_fu_1931_p0 = r_V_8_fu_1931_p00;

assign r_V_8_fu_1931_p00 = p_Val2_54_lcssa_reg_357_pp0_iter2_reg;

assign r_V_8_fu_1931_p1 = r_V_8_fu_1931_p10;

assign r_V_8_fu_1931_p10 = b_frac_tilde_inverse_reg_2457;

assign r_V_8_fu_1931_p2 = (r_V_8_fu_1931_p0 * r_V_8_fu_1931_p1);

assign r_V_s_fu_2078_p4 = {{r_V_10_fu_2072_p2[17:1]}};

assign ret_V_1_fu_2103_p2 = (zext_ln728_fu_2095_p1 - zext_ln703_2_fu_2099_p1);

assign select_ln730_1_fu_1880_p3 = ((trunc_ln730_fu_1806_p1[0:0] === 1'b1) ? st_fu_1872_p3 : 35'd0);

assign select_ln730_fu_1864_p3 = ((trunc_ln730_fu_1806_p1[0:0] === 1'b1) ? 5'd19 : 5'd18);

assign sext_ln703_1_fu_2148_p1 = $signed(add_ln703_22_reg_2511);

assign sext_ln703_2_fu_2179_p1 = $signed(shl_ln703_1_fu_2171_p3);

assign sext_ln703_fu_2144_p1 = $signed(shl_ln1_fu_2137_p3);

assign sf_fu_1973_p3 = {{5'd16}, {tmp_s_fu_1964_p4}};

assign shl_ln1299_10_fu_1148_p3 = {{trunc_ln1299_10_fu_1144_p1}, {19'd0}};

assign shl_ln1299_11_fu_1198_p3 = {{trunc_ln1299_11_fu_1194_p1}, {20'd0}};

assign shl_ln1299_12_fu_1248_p3 = {{trunc_ln1299_12_fu_1244_p1}, {21'd0}};

assign shl_ln1299_13_fu_1298_p3 = {{trunc_ln1299_13_fu_1294_p1}, {22'd0}};

assign shl_ln1299_14_fu_1348_p3 = {{trunc_ln1299_14_fu_1344_p1}, {23'd0}};

assign shl_ln1299_15_fu_1398_p3 = {{trunc_ln1299_15_fu_1394_p1}, {24'd0}};

assign shl_ln1299_16_fu_1448_p3 = {{trunc_ln1299_16_fu_1444_p1}, {25'd0}};

assign shl_ln1299_17_fu_1498_p3 = {{trunc_ln1299_17_fu_1494_p1}, {26'd0}};

assign shl_ln1299_18_fu_1548_p3 = {{trunc_ln1299_18_fu_1544_p1}, {27'd0}};

assign shl_ln1299_19_fu_1598_p3 = {{trunc_ln1299_19_fu_1594_p1}, {28'd0}};

assign shl_ln1299_1_fu_648_p3 = {{trunc_ln1299_fu_644_p1}, {9'd0}};

assign shl_ln1299_20_fu_1648_p3 = {{trunc_ln1299_20_fu_1644_p1}, {29'd0}};

assign shl_ln1299_21_fu_1698_p3 = {{trunc_ln1299_21_fu_1694_p1}, {30'd0}};

assign shl_ln1299_22_fu_1748_p3 = {{trunc_ln1299_22_fu_1744_p1}, {31'd0}};

assign shl_ln1299_23_fu_1798_p3 = {{trunc_ln1299_23_fu_1794_p1}, {32'd0}};

assign shl_ln1299_24_fu_1844_p3 = {{trunc_ln1299_24_fu_1840_p1}, {33'd0}};

assign shl_ln1299_2_fu_698_p3 = {{trunc_ln1299_1_fu_694_p1}, {10'd0}};

assign shl_ln1299_3_fu_748_p3 = {{trunc_ln1299_2_fu_744_p1}, {11'd0}};

assign shl_ln1299_4_fu_798_p3 = {{trunc_ln1299_3_fu_794_p1}, {12'd0}};

assign shl_ln1299_5_fu_848_p3 = {{trunc_ln1299_4_fu_844_p1}, {13'd0}};

assign shl_ln1299_6_fu_898_p3 = {{trunc_ln1299_5_fu_894_p1}, {14'd0}};

assign shl_ln1299_7_fu_948_p3 = {{trunc_ln1299_6_fu_944_p1}, {15'd0}};

assign shl_ln1299_8_fu_998_p3 = {{trunc_ln1299_7_fu_994_p1}, {16'd0}};

assign shl_ln1299_9_fu_1048_p3 = {{trunc_ln1299_8_fu_1044_p1}, {17'd0}};

assign shl_ln1299_s_fu_1098_p3 = {{trunc_ln1299_9_fu_1094_p1}, {18'd0}};

assign shl_ln1_fu_2137_p3 = {{tmp_34_reg_2506}, {6'd0}};

assign shl_ln703_1_fu_2171_p3 = {{p_Result_7_fu_2163_p3}, {9'd256}};

assign shl_ln_fu_598_p3 = {{x_V}, {8'd0}};

assign st_fu_1872_p3 = {{trunc_ln730_fu_1806_p1}, {34'd0}};

assign sum_V_fu_2134_p1 = $signed(trunc_ln708_s_reg_2501);

assign tmp_31_fu_1981_p3 = {{5'd16}, {z1_V_reg_2474}};

assign tmp_32_fu_2000_p4 = {{r_V_8_reg_2467[30:11]}};

assign tmp_43_fu_578_p3 = x_V[32'd25];

assign tmp_44_fu_606_p3 = x_V[32'd24];

assign tmp_45_fu_656_p3 = x_V[32'd23];

assign tmp_46_fu_706_p3 = x_V[32'd22];

assign tmp_47_fu_756_p3 = x_V[32'd21];

assign tmp_48_fu_806_p3 = x_V[32'd20];

assign tmp_49_fu_856_p3 = x_V[32'd19];

assign tmp_50_fu_906_p3 = x_V[32'd18];

assign tmp_51_fu_956_p3 = x_V[32'd17];

assign tmp_52_fu_1006_p3 = x_V[32'd16];

assign tmp_53_fu_1056_p3 = x_V[32'd15];

assign tmp_54_fu_1106_p3 = x_V[32'd14];

assign tmp_55_fu_1156_p3 = x_V[32'd13];

assign tmp_56_fu_1206_p3 = x_V[32'd12];

assign tmp_57_fu_1256_p3 = x_V[32'd11];

assign tmp_63_fu_1306_p3 = x_V[32'd10];

assign tmp_64_fu_1356_p3 = x_V[32'd9];

assign tmp_65_fu_1406_p3 = x_V[32'd8];

assign tmp_66_fu_1456_p3 = x_V[32'd7];

assign tmp_67_fu_1506_p3 = x_V[32'd6];

assign tmp_68_fu_1556_p3 = x_V[32'd5];

assign tmp_69_fu_1606_p3 = x_V[32'd4];

assign tmp_70_fu_1656_p3 = x_V[32'd3];

assign tmp_71_fu_1706_p3 = x_V[32'd2];

assign tmp_72_fu_1756_p3 = x_V[32'd1];

assign tmp_74_fu_1957_p3 = r_V_8_reg_2467[32'd34];

assign tmp_fu_570_p3 = x_V[32'd26];

assign tmp_s_fu_1964_p4 = {{r_V_8_reg_2467[34:12]}};

assign trunc_ln1299_10_fu_1144_p1 = x_V[15:0];

assign trunc_ln1299_11_fu_1194_p1 = x_V[14:0];

assign trunc_ln1299_12_fu_1244_p1 = x_V[13:0];

assign trunc_ln1299_13_fu_1294_p1 = x_V[12:0];

assign trunc_ln1299_14_fu_1344_p1 = x_V[11:0];

assign trunc_ln1299_15_fu_1394_p1 = x_V[10:0];

assign trunc_ln1299_16_fu_1444_p1 = x_V[9:0];

assign trunc_ln1299_17_fu_1494_p1 = x_V[8:0];

assign trunc_ln1299_18_fu_1544_p1 = x_V[7:0];

assign trunc_ln1299_19_fu_1594_p1 = x_V[6:0];

assign trunc_ln1299_1_fu_694_p1 = x_V[24:0];

assign trunc_ln1299_20_fu_1644_p1 = x_V[5:0];

assign trunc_ln1299_21_fu_1694_p1 = x_V[4:0];

assign trunc_ln1299_22_fu_1744_p1 = x_V[3:0];

assign trunc_ln1299_23_fu_1794_p1 = x_V[2:0];

assign trunc_ln1299_24_fu_1840_p1 = x_V[1:0];

assign trunc_ln1299_2_fu_744_p1 = x_V[23:0];

assign trunc_ln1299_3_fu_794_p1 = x_V[22:0];

assign trunc_ln1299_4_fu_844_p1 = x_V[21:0];

assign trunc_ln1299_5_fu_894_p1 = x_V[20:0];

assign trunc_ln1299_6_fu_944_p1 = x_V[19:0];

assign trunc_ln1299_7_fu_994_p1 = x_V[18:0];

assign trunc_ln1299_8_fu_1044_p1 = x_V[17:0];

assign trunc_ln1299_9_fu_1094_p1 = x_V[16:0];

assign trunc_ln1299_fu_644_p1 = x_V[25:0];

assign trunc_ln708_23_fu_2189_p4 = {{log_base_V_1_fu_2183_p2[28:9]}};

assign trunc_ln730_fu_1806_p1 = x_V[0:0];

assign xor_ln730_10_fu_1076_p2 = (tmp_52_fu_1006_p3 ^ 1'd1);

assign xor_ln730_11_fu_1126_p2 = (tmp_53_fu_1056_p3 ^ 1'd1);

assign xor_ln730_12_fu_1176_p2 = (tmp_54_fu_1106_p3 ^ 1'd1);

assign xor_ln730_13_fu_1226_p2 = (tmp_55_fu_1156_p3 ^ 1'd1);

assign xor_ln730_14_fu_1276_p2 = (tmp_56_fu_1206_p3 ^ 1'd1);

assign xor_ln730_15_fu_1326_p2 = (tmp_57_fu_1256_p3 ^ 1'd1);

assign xor_ln730_16_fu_1376_p2 = (tmp_63_fu_1306_p3 ^ 1'd1);

assign xor_ln730_17_fu_1426_p2 = (tmp_64_fu_1356_p3 ^ 1'd1);

assign xor_ln730_18_fu_1476_p2 = (tmp_65_fu_1406_p3 ^ 1'd1);

assign xor_ln730_19_fu_1526_p2 = (tmp_66_fu_1456_p3 ^ 1'd1);

assign xor_ln730_1_fu_626_p2 = (tmp_43_fu_578_p3 ^ 1'd1);

assign xor_ln730_20_fu_1576_p2 = (tmp_67_fu_1506_p3 ^ 1'd1);

assign xor_ln730_21_fu_1626_p2 = (tmp_68_fu_1556_p3 ^ 1'd1);

assign xor_ln730_22_fu_1676_p2 = (tmp_69_fu_1606_p3 ^ 1'd1);

assign xor_ln730_23_fu_1726_p2 = (tmp_70_fu_1656_p3 ^ 1'd1);

assign xor_ln730_24_fu_1776_p2 = (tmp_71_fu_1706_p3 ^ 1'd1);

assign xor_ln730_25_fu_1822_p2 = (tmp_72_fu_1756_p3 ^ 1'd1);

assign xor_ln730_26_fu_1852_p2 = (trunc_ln730_fu_1806_p1 ^ 1'd1);

assign xor_ln730_2_fu_676_p2 = (tmp_44_fu_606_p3 ^ 1'd1);

assign xor_ln730_3_fu_726_p2 = (tmp_45_fu_656_p3 ^ 1'd1);

assign xor_ln730_4_fu_776_p2 = (tmp_46_fu_706_p3 ^ 1'd1);

assign xor_ln730_5_fu_826_p2 = (tmp_47_fu_756_p3 ^ 1'd1);

assign xor_ln730_6_fu_876_p2 = (tmp_48_fu_806_p3 ^ 1'd1);

assign xor_ln730_7_fu_926_p2 = (tmp_49_fu_856_p3 ^ 1'd1);

assign xor_ln730_8_fu_976_p2 = (tmp_50_fu_906_p3 ^ 1'd1);

assign xor_ln730_9_fu_1026_p2 = (tmp_51_fu_956_p3 ^ 1'd1);

assign xor_ln730_fu_592_p2 = (tmp_fu_570_p3 ^ 1'd1);

assign zext_ln1116_fu_2069_p1 = trunc_ln_reg_2496;

assign zext_ln1333_fu_1988_p1 = sf_fu_1973_p3;

assign zext_ln203_fu_2065_p1 = log_apfixed_reduce_s_q0;

assign zext_ln544_1_fu_2033_p1 = a_V_reg_2480;

assign zext_ln544_fu_1918_p1 = ap_phi_mux_index0_V_phi_fu_422_p4;

assign zext_ln703_2_fu_2099_p1 = r_V_s_fu_2078_p4;

assign zext_ln703_fu_2017_p1 = lhs_V_fu_2009_p3;

assign zext_ln728_fu_2095_p1 = lhs_V_1_fu_2088_p3;

endmodule //log_28_15_s
