// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2019.1
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module sqrt_fixed_28_15_s (
        ap_clk,
        ap_rst,
        x_V,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [17:0] x_V;
output  [20:0] ap_return;
input   ap_ce;

reg[20:0] ap_return;

wire   [12:0] trunc_ln731_fu_238_p1;
reg   [12:0] trunc_ln731_reg_2758;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln488_4_fu_422_p3;
reg   [7:0] select_ln488_4_reg_2763;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter1_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter2_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter3_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter4_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter5_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter6_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter7_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter8_reg;
reg   [7:0] select_ln488_4_reg_2763_pp0_iter9_reg;
wire   [17:0] select_ln488_5_fu_430_p3;
reg   [17:0] select_ln488_5_reg_2776;
wire   [0:0] icmp_ln1495_fu_448_p2;
reg   [0:0] icmp_ln1495_reg_2784;
wire   [17:0] add_ln703_fu_454_p2;
reg   [17:0] add_ln703_reg_2789;
wire   [0:0] icmp_ln318_fu_470_p2;
reg   [0:0] icmp_ln318_reg_2794;
reg   [6:0] tmp_5_reg_2799;
wire   [0:0] trunc_ln708_fu_486_p1;
reg   [0:0] trunc_ln708_reg_2804;
reg   [5:0] tmp_11_reg_2809;
reg   [5:0] tmp_11_reg_2809_pp0_iter1_reg;
wire   [1:0] trunc_ln708_21_fu_500_p1;
reg   [1:0] trunc_ln708_21_reg_2814;
reg   [1:0] trunc_ln708_21_reg_2814_pp0_iter1_reg;
reg   [4:0] tmp_13_reg_2819;
reg   [4:0] tmp_13_reg_2819_pp0_iter1_reg;
wire   [2:0] trunc_ln708_22_fu_514_p1;
reg   [2:0] trunc_ln708_22_reg_2824;
reg   [2:0] trunc_ln708_22_reg_2824_pp0_iter1_reg;
reg   [3:0] tmp_15_reg_2829;
reg   [3:0] tmp_15_reg_2829_pp0_iter1_reg;
reg   [3:0] tmp_15_reg_2829_pp0_iter2_reg;
wire   [3:0] trunc_ln708_23_fu_528_p1;
reg   [3:0] trunc_ln708_23_reg_2834;
reg   [3:0] trunc_ln708_23_reg_2834_pp0_iter1_reg;
reg   [3:0] trunc_ln708_23_reg_2834_pp0_iter2_reg;
reg   [2:0] tmp_17_reg_2839;
reg   [2:0] tmp_17_reg_2839_pp0_iter1_reg;
reg   [2:0] tmp_17_reg_2839_pp0_iter2_reg;
reg   [2:0] tmp_17_reg_2839_pp0_iter3_reg;
wire   [4:0] trunc_ln708_24_fu_542_p1;
reg   [4:0] trunc_ln708_24_reg_2844;
reg   [4:0] trunc_ln708_24_reg_2844_pp0_iter1_reg;
reg   [4:0] trunc_ln708_24_reg_2844_pp0_iter2_reg;
reg   [4:0] trunc_ln708_24_reg_2844_pp0_iter3_reg;
reg   [1:0] tmp_19_reg_2849;
reg   [1:0] tmp_19_reg_2849_pp0_iter1_reg;
reg   [1:0] tmp_19_reg_2849_pp0_iter2_reg;
reg   [1:0] tmp_19_reg_2849_pp0_iter3_reg;
wire   [5:0] trunc_ln708_25_fu_556_p1;
reg   [5:0] trunc_ln708_25_reg_2854;
reg   [5:0] trunc_ln708_25_reg_2854_pp0_iter1_reg;
reg   [5:0] trunc_ln708_25_reg_2854_pp0_iter2_reg;
reg   [5:0] trunc_ln708_25_reg_2854_pp0_iter3_reg;
reg   [0:0] tmp_32_reg_2859;
reg   [0:0] tmp_32_reg_2859_pp0_iter1_reg;
reg   [0:0] tmp_32_reg_2859_pp0_iter2_reg;
reg   [0:0] tmp_32_reg_2859_pp0_iter3_reg;
reg   [0:0] tmp_32_reg_2859_pp0_iter4_reg;
wire   [6:0] trunc_ln708_26_fu_568_p1;
reg   [6:0] trunc_ln708_26_reg_2864;
reg   [6:0] trunc_ln708_26_reg_2864_pp0_iter1_reg;
reg   [6:0] trunc_ln708_26_reg_2864_pp0_iter2_reg;
reg   [6:0] trunc_ln708_26_reg_2864_pp0_iter3_reg;
reg   [6:0] trunc_ln708_26_reg_2864_pp0_iter4_reg;
wire   [13:0] select_ln318_fu_628_p3;
reg   [13:0] select_ln318_reg_2869;
wire   [17:0] select_ln318_2_fu_644_p3;
reg   [17:0] select_ln318_2_reg_2875;
wire   [17:0] sub_ln703_2_fu_719_p2;
reg   [17:0] sub_ln703_2_reg_2880;
wire   [0:0] or_ln318_1_fu_743_p2;
reg   [0:0] or_ln318_1_reg_2885;
wire   [13:0] select_ln318_4_fu_749_p3;
reg   [13:0] select_ln318_4_reg_2891;
wire   [13:0] select_ln318_6_fu_882_p3;
reg   [13:0] select_ln318_6_reg_2899;
wire   [13:0] select_ln318_7_fu_890_p3;
reg   [13:0] select_ln318_7_reg_2905;
wire   [17:0] select_ln318_8_fu_897_p3;
reg   [17:0] select_ln318_8_reg_2911;
wire   [13:0] trunc_ln708_8_fu_922_p4;
reg   [13:0] trunc_ln708_8_reg_2917;
wire   [17:0] zext_ln1494_3_fu_931_p1;
reg   [17:0] zext_ln1494_3_reg_2922;
wire   [0:0] icmp_ln1494_3_fu_935_p2;
reg   [0:0] icmp_ln1494_3_reg_2927;
wire   [0:0] icmp_ln1498_3_fu_941_p2;
reg   [0:0] icmp_ln1498_3_reg_2932;
wire   [0:0] icmp_ln1495_3_fu_947_p2;
reg   [0:0] icmp_ln1495_3_reg_2937;
wire   [17:0] add_ln703_3_fu_953_p2;
reg   [17:0] add_ln703_3_reg_2942;
wire   [0:0] icmp_ln318_3_fu_959_p2;
reg   [0:0] icmp_ln318_3_reg_2947;
wire   [13:0] select_ln318_12_fu_1132_p3;
reg   [13:0] select_ln318_12_reg_2952;
wire   [13:0] select_ln318_13_fu_1140_p3;
reg   [13:0] select_ln318_13_reg_2958;
wire   [17:0] select_ln318_14_fu_1148_p3;
reg   [17:0] select_ln318_14_reg_2966;
reg   [5:0] p_Result_34_5_reg_2975;
wire   [13:0] select_ln318_15_fu_1255_p3;
reg   [13:0] select_ln318_15_reg_2980;
wire   [13:0] select_ln318_16_fu_1262_p3;
reg   [13:0] select_ln318_16_reg_2986;
wire   [17:0] select_ln318_17_fu_1269_p3;
reg   [17:0] select_ln318_17_reg_2992;
wire   [13:0] trunc_ln708_12_fu_1293_p4;
reg   [13:0] trunc_ln708_12_reg_2998;
wire   [17:0] zext_ln1494_6_fu_1302_p1;
reg   [17:0] zext_ln1494_6_reg_3003;
wire   [0:0] icmp_ln1495_6_fu_1318_p2;
reg   [0:0] icmp_ln1495_6_reg_3008;
wire   [17:0] add_ln703_6_fu_1324_p2;
reg   [17:0] add_ln703_6_reg_3013;
wire   [0:0] or_ln318_6_fu_1348_p2;
reg   [0:0] or_ln318_6_reg_3018;
wire   [13:0] select_ln318_18_fu_1377_p3;
reg   [13:0] select_ln318_18_reg_3025;
wire   [13:0] sub_ln703_13_fu_1493_p2;
reg   [13:0] sub_ln703_13_reg_3031;
wire   [0:0] or_ln318_10_fu_1575_p2;
reg   [0:0] or_ln318_10_reg_3036;
wire   [13:0] select_ln318_23_fu_1581_p3;
reg   [13:0] select_ln318_23_reg_3042;
wire   [17:0] select_ln318_24_fu_1589_p3;
reg   [17:0] select_ln318_24_reg_3052;
wire   [13:0] select_ln318_25_fu_1784_p3;
reg   [13:0] select_ln318_25_reg_3061;
wire   [13:0] select_ln318_26_fu_1792_p3;
reg   [13:0] select_ln318_26_reg_3067;
wire   [13:0] select_ln318_27_fu_1800_p3;
reg   [13:0] select_ln318_27_reg_3073;
wire   [17:0] select_ln318_28_fu_1807_p3;
reg   [17:0] select_ln318_28_reg_3083;
reg   [4:0] tmp_25_reg_3092;
wire   [13:0] mul_FL_V_9_fu_1834_p3;
reg   [13:0] mul_FL_V_9_reg_3097;
wire   [0:0] icmp_ln1496_2_fu_1842_p2;
reg   [0:0] icmp_ln1496_2_reg_3102;
wire   [13:0] p_neg_9_fu_1848_p3;
reg   [13:0] p_neg_9_reg_3108;
wire   [13:0] select_ln318_29_fu_1975_p3;
reg   [13:0] select_ln318_29_reg_3113;
wire   [13:0] select_ln318_31_fu_1989_p3;
reg   [13:0] select_ln318_31_reg_3119;
wire   [13:0] trunc_ln708_17_fu_2023_p4;
reg   [13:0] trunc_ln708_17_reg_3125;
wire   [13:0] p_neg_10_fu_2118_p3;
reg   [13:0] p_neg_10_reg_3130;
wire   [0:0] or_ln318_25_fu_2152_p2;
reg   [0:0] or_ln318_25_reg_3135;
wire   [13:0] select_ln318_34_fu_2158_p3;
reg   [13:0] select_ln318_34_reg_3141;
wire   [17:0] select_ln318_36_fu_2166_p3;
reg   [17:0] select_ln318_36_reg_3148;
wire   [13:0] select_ln318_33_fu_2192_p3;
reg   [13:0] select_ln318_33_reg_3157;
wire   [13:0] select_ln318_35_fu_2198_p3;
reg   [13:0] select_ln318_35_reg_3163;
wire   [13:0] add_ln703_15_fu_2329_p2;
reg   [13:0] add_ln703_15_reg_3168;
wire   [0:0] or_ln318_28_fu_2359_p2;
reg   [0:0] or_ln318_28_reg_3173;
wire   [13:0] select_ln318_38_fu_2365_p3;
reg   [13:0] select_ln318_38_reg_3179;
wire   [17:0] select_ln318_40_fu_2372_p3;
reg   [17:0] select_ln318_40_reg_3186;
wire   [13:0] select_ln318_41_fu_2570_p3;
reg   [13:0] select_ln318_41_reg_3195;
wire   [13:0] select_ln318_43_fu_2585_p3;
reg   [13:0] select_ln318_43_reg_3201;
reg   [0:0] tmp_39_reg_3207;
wire   [0:0] icmp_ln1494_13_fu_2620_p2;
reg   [0:0] icmp_ln1494_13_reg_3212;
wire   [0:0] icmp_ln1498_13_fu_2626_p2;
reg   [0:0] icmp_ln1498_13_reg_3218;
wire   [0:0] icmp_ln1496_6_fu_2632_p2;
reg   [0:0] icmp_ln1496_6_reg_3223;
wire    ap_block_pp0_stage0;
wire   [4:0] tmp_fu_224_p4;
wire   [0:0] tmp_4_fu_242_p3;
wire   [0:0] xor_ln248_fu_250_p2;
wire   [17:0] x_l_I_V_fu_234_p1;
wire   [7:0] select_ln248_fu_256_p3;
wire   [17:0] p_Result_30_5_fu_264_p5;
wire   [1:0] select_ln488_6_fu_292_p3;
wire   [17:0] select_ln488_1_fu_284_p3;
wire   [2:0] tmp_6_fu_300_p3;
wire   [8:0] p_Result_28_6_fu_308_p4;
wire   [8:0] zext_ln488_fu_318_p1;
wire   [8:0] sub_ln248_fu_328_p2;
wire   [7:0] select_ln488_fu_276_p3;
wire   [0:0] icmp_ln488_fu_322_p2;
reg   [7:0] tmp_8_fu_346_p4;
wire   [17:0] p_Result_30_6_fu_334_p5;
wire   [7:0] select_ln488_2_fu_356_p3;
wire   [17:0] select_ln488_3_fu_364_p3;
wire   [8:0] tmp_7_fu_372_p3;
wire   [9:0] trunc_ln612_fu_380_p1;
wire   [9:0] zext_ln488_1_fu_384_p1;
wire   [9:0] sub_ln248_1_fu_394_p2;
wire   [0:0] icmp_ln488_1_fu_388_p2;
reg   [7:0] tmp_10_fu_412_p4;
wire   [17:0] p_Result_30_7_fu_400_p5;
wire   [1:0] tmp_12_fu_438_p4;
wire   [1:0] tmp_14_fu_460_p4;
wire   [15:0] trunc_ln708_1_fu_579_p3;
wire   [17:0] zext_ln1494_fu_586_p1;
wire   [13:0] x_l_FH_V_fu_572_p3;
wire   [17:0] select_ln339_fu_606_p3;
wire   [0:0] icmp_ln1498_fu_595_p2;
wire   [0:0] and_ln318_fu_617_p2;
wire   [0:0] icmp_ln1494_fu_590_p2;
wire   [0:0] or_ln318_fu_622_p2;
wire   [13:0] add_ln703_19_fu_600_p2;
wire   [17:0] sub_ln703_fu_611_p2;
wire   [1:0] p_Result_34_1_fu_651_p4;
wire   [15:0] trunc_ln708_3_fu_661_p3;
wire   [17:0] zext_ln1494_1_fu_677_p1;
wire   [13:0] select_ln318_1_fu_636_p3;
wire   [13:0] trunc_ln708_4_fu_668_p4;
wire   [0:0] icmp_ln1495_1_fu_693_p2;
wire   [17:0] add_ln703_1_fu_705_p2;
wire   [17:0] select_ln339_1_fu_711_p3;
wire   [0:0] icmp_ln318_1_fu_725_p2;
wire   [0:0] icmp_ln1498_1_fu_687_p2;
wire   [0:0] xor_ln318_7_fu_731_p2;
wire   [0:0] and_ln318_1_fu_737_p2;
wire   [0:0] icmp_ln1494_1_fu_681_p2;
wire   [13:0] sub_ln703_1_fu_699_p2;
reg   [13:0] tmp_16_fu_757_p4;
wire   [13:0] select_ln318_3_fu_766_p3;
wire   [2:0] p_Result_34_2_fu_777_p4;
wire   [15:0] trunc_ln708_5_fu_787_p3;
wire   [17:0] select_ln318_5_fu_772_p3;
wire   [17:0] zext_ln1494_2_fu_803_p1;
wire   [13:0] trunc_ln708_6_fu_794_p4;
wire   [0:0] icmp_ln1495_2_fu_819_p2;
wire   [17:0] add_ln703_2_fu_829_p2;
wire   [17:0] select_ln339_2_fu_835_p3;
wire   [0:0] icmp_ln318_2_fu_859_p2;
wire   [0:0] icmp_ln1498_2_fu_813_p2;
wire   [0:0] xor_ln318_8_fu_864_p2;
wire   [0:0] and_ln318_2_fu_870_p2;
wire   [0:0] icmp_ln1494_2_fu_807_p2;
wire   [0:0] or_ln318_2_fu_876_p2;
reg   [13:0] tmp_18_fu_849_p4;
wire   [13:0] sub_ln703_3_fu_824_p2;
wire   [17:0] sub_ln703_4_fu_843_p2;
wire   [3:0] p_Result_34_3_fu_905_p4;
wire   [15:0] trunc_ln708_7_fu_915_p3;
wire   [17:0] select_ln339_3_fu_969_p3;
wire   [0:0] xor_ln318_9_fu_988_p2;
wire   [0:0] and_ln318_3_fu_993_p2;
wire   [0:0] or_ln318_3_fu_998_p2;
reg   [13:0] tmp_20_fu_979_p4;
wire   [13:0] sub_ln703_5_fu_965_p2;
wire   [17:0] sub_ln703_6_fu_974_p2;
wire   [13:0] select_ln318_9_fu_1003_p3;
wire   [4:0] p_Result_34_4_fu_1024_p4;
wire   [15:0] trunc_ln708_9_fu_1034_p3;
wire   [17:0] select_ln318_11_fu_1017_p3;
wire   [17:0] zext_ln1494_4_fu_1050_p1;
wire   [13:0] select_ln318_10_fu_1010_p3;
wire   [13:0] trunc_ln708_s_fu_1041_p4;
wire   [0:0] icmp_ln1495_4_fu_1066_p2;
wire   [17:0] add_ln703_4_fu_1078_p2;
wire   [17:0] select_ln339_4_fu_1084_p3;
wire   [0:0] icmp_ln318_4_fu_1108_p2;
wire   [0:0] icmp_ln1498_4_fu_1060_p2;
wire   [0:0] xor_ln318_10_fu_1114_p2;
wire   [0:0] and_ln318_4_fu_1120_p2;
wire   [0:0] icmp_ln1494_4_fu_1054_p2;
wire   [0:0] or_ln318_4_fu_1126_p2;
reg   [13:0] tmp_21_fu_1098_p4;
wire   [13:0] sub_ln703_7_fu_1072_p2;
wire   [17:0] sub_ln703_8_fu_1092_p2;
wire   [15:0] trunc_ln708_2_fu_1166_p3;
wire   [17:0] zext_ln1494_5_fu_1181_p1;
wire   [13:0] trunc_ln708_10_fu_1173_p4;
wire   [0:0] icmp_ln1495_5_fu_1195_p2;
wire   [17:0] add_ln703_5_fu_1205_p2;
wire   [17:0] select_ln339_5_fu_1210_p3;
wire   [0:0] icmp_ln318_5_fu_1232_p2;
wire   [0:0] icmp_ln1498_5_fu_1190_p2;
wire   [0:0] xor_ln318_11_fu_1237_p2;
wire   [0:0] and_ln318_5_fu_1243_p2;
wire   [0:0] icmp_ln1494_5_fu_1185_p2;
wire   [0:0] or_ln318_5_fu_1249_p2;
reg   [13:0] tmp_23_fu_1223_p4;
wire   [13:0] sub_ln703_9_fu_1200_p2;
wire   [17:0] sub_ln703_10_fu_1217_p2;
wire   [6:0] p_Result_34_6_fu_1276_p4;
wire   [15:0] trunc_ln708_11_fu_1286_p3;
wire   [0:0] icmp_ln318_6_fu_1330_p2;
wire   [0:0] icmp_ln1498_6_fu_1312_p2;
wire   [0:0] xor_ln318_12_fu_1336_p2;
wire   [0:0] and_ln318_6_fu_1342_p2;
wire   [0:0] icmp_ln1494_6_fu_1306_p2;
wire   [17:0] select_ln339_6_fu_1358_p3;
reg   [13:0] tmp_29_fu_1368_p4;
wire   [13:0] sub_ln703_11_fu_1354_p2;
wire   [17:0] sub_ln703_12_fu_1363_p2;
wire   [6:0] tmp_22_fu_1410_p4;
wire   [0:0] tmp_31_fu_1395_p3;
wire   [15:0] trunc_ln708_13_fu_1403_p3;
wire   [17:0] select_ln318_20_fu_1389_p3;
wire   [17:0] zext_ln1494_7_fu_1435_p1;
wire   [13:0] select_ln318_19_fu_1383_p3;
wire   [13:0] trunc_ln708_14_fu_1420_p3;
wire   [0:0] icmp_ln1498_7_fu_1445_p2;
wire   [0:0] icmp_ln1494_14_fu_1451_p2;
wire   [13:0] mul_FL_V_7_fu_1427_p3;
wire   [0:0] icmp_ln318_7_fu_1463_p2;
wire   [0:0] icmp_ln1496_fu_1475_p2;
wire   [0:0] or_ln318_7_fu_1481_p2;
wire   [0:0] icmp_ln318_8_fu_1469_p2;
wire   [0:0] icmp_ln1498_14_fu_1505_p2;
wire   [0:0] icmp_ln1495_7_fu_1499_p2;
wire   [0:0] and_ln331_fu_1511_p2;
wire   [13:0] p_neg_7_fu_1523_p3;
wire   [13:0] sub_ln703_14_fu_1531_p2;
wire   [0:0] or_ln331_fu_1517_p2;
wire   [17:0] add_ln703_8_fu_1543_p2;
wire   [17:0] select_ln339_7_fu_1549_p3;
wire   [0:0] or_ln318_8_fu_1487_p2;
wire   [0:0] and_ln318_7_fu_1457_p2;
wire   [0:0] xor_ln318_fu_1563_p2;
wire   [0:0] or_ln318_9_fu_1569_p2;
wire   [0:0] icmp_ln1494_7_fu_1439_p2;
wire   [13:0] add_ln703_7_fu_1537_p2;
wire   [17:0] sub_ln703_15_fu_1557_p2;
reg   [13:0] tmp_33_fu_1597_p4;
wire   [13:0] select_ln318_21_fu_1606_p3;
wire   [5:0] tmp_24_fu_1628_p4;
wire   [2:0] tmp_9_fu_1618_p4;
wire   [13:0] trunc_ln708_15_fu_1638_p3;
wire   [0:0] icmp_ln1498_8_fu_1658_p2;
wire   [0:0] icmp_ln1494_15_fu_1663_p2;
wire   [13:0] select_ln318_22_fu_1612_p3;
wire   [13:0] mul_FL_V_8_fu_1645_p3;
wire   [0:0] icmp_ln1494_8_fu_1653_p2;
wire   [0:0] icmp_ln1496_1_fu_1679_p2;
wire   [0:0] or_ln318_11_fu_1685_p2;
wire   [0:0] icmp_ln318_9_fu_1674_p2;
wire   [0:0] icmp_ln1498_15_fu_1708_p2;
wire   [0:0] icmp_ln1495_8_fu_1703_p2;
wire   [0:0] and_ln331_1_fu_1713_p2;
wire   [13:0] p_neg_8_fu_1725_p3;
wire   [13:0] sub_ln703_17_fu_1733_p2;
wire   [0:0] or_ln331_1_fu_1719_p2;
wire   [17:0] add_ln703_10_fu_1744_p2;
wire   [0:0] or_ln318_12_fu_1691_p2;
wire   [0:0] and_ln318_8_fu_1668_p2;
wire   [0:0] xor_ln318_1_fu_1766_p2;
wire   [0:0] or_ln318_13_fu_1772_p2;
wire   [0:0] or_ln318_14_fu_1778_p2;
reg   [13:0] tmp_34_fu_1756_p4;
wire   [13:0] sub_ln703_16_fu_1697_p2;
wire   [13:0] add_ln703_9_fu_1739_p2;
wire   [17:0] select_ln339_8_fu_1749_p3;
wire   [4:0] tmp_s_fu_1814_p4;
wire   [13:0] trunc_ln708_16_fu_1856_p4;
wire   [0:0] icmp_ln1498_9_fu_1869_p2;
wire   [0:0] icmp_ln1494_16_fu_1874_p2;
wire   [0:0] icmp_ln1494_9_fu_1864_p2;
wire   [0:0] or_ln318_15_fu_1890_p2;
wire   [0:0] icmp_ln318_10_fu_1885_p2;
wire   [0:0] icmp_ln1498_16_fu_1910_p2;
wire   [0:0] icmp_ln1495_9_fu_1905_p2;
wire   [0:0] and_ln331_2_fu_1915_p2;
wire   [13:0] sub_ln703_19_fu_1926_p2;
wire   [0:0] or_ln331_2_fu_1920_p2;
wire   [17:0] add_ln703_12_fu_1936_p2;
wire   [0:0] or_ln318_16_fu_1895_p2;
wire   [0:0] and_ln318_9_fu_1879_p2;
wire   [0:0] xor_ln318_2_fu_1957_p2;
wire   [0:0] or_ln318_21_fu_1963_p2;
wire   [0:0] or_ln318_22_fu_1969_p2;
reg   [13:0] tmp_35_fu_1948_p4;
wire   [13:0] sub_ln703_18_fu_1901_p2;
wire   [13:0] add_ln703_11_fu_1931_p2;
wire   [17:0] select_ln339_9_fu_1941_p3;
wire   [3:0] tmp_26_fu_2013_p4;
wire   [6:0] tmp_1_fu_2003_p4;
wire   [17:0] select_ln318_32_fu_1996_p3;
wire   [0:0] icmp_ln1498_10_fu_2046_p2;
wire   [0:0] icmp_ln1494_17_fu_2052_p2;
wire   [13:0] select_ln318_30_fu_1982_p3;
wire   [13:0] mul_FL_V_s_fu_2032_p3;
wire   [0:0] icmp_ln1494_10_fu_2040_p2;
wire   [0:0] icmp_ln1496_3_fu_2070_p2;
wire   [0:0] or_ln318_23_fu_2076_p2;
wire   [0:0] icmp_ln318_11_fu_2064_p2;
wire   [0:0] icmp_ln1498_17_fu_2100_p2;
wire   [0:0] icmp_ln1495_10_fu_2094_p2;
wire   [0:0] and_ln331_3_fu_2106_p2;
wire   [0:0] or_ln331_3_fu_2112_p2;
wire   [17:0] add_ln703_14_fu_2126_p2;
wire   [0:0] or_ln318_17_fu_2082_p2;
wire   [0:0] and_ln318_10_fu_2058_p2;
wire   [0:0] xor_ln318_3_fu_2140_p2;
wire   [0:0] or_ln318_24_fu_2146_p2;
wire   [13:0] sub_ln703_20_fu_2088_p2;
wire   [17:0] select_ln339_10_fu_2132_p3;
wire   [13:0] sub_ln703_21_fu_2174_p2;
reg   [13:0] tmp_36_fu_2183_p4;
wire   [13:0] add_ln703_13_fu_2178_p2;
wire   [2:0] tmp_27_fu_2214_p4;
wire   [8:0] tmp_2_fu_2204_p4;
wire   [13:0] trunc_ln708_18_fu_2224_p4;
wire   [0:0] icmp_ln1498_11_fu_2246_p2;
wire   [0:0] icmp_ln1494_18_fu_2251_p2;
wire   [13:0] mul_FL_V_1_fu_2233_p3;
wire   [0:0] icmp_ln1494_11_fu_2241_p2;
wire   [0:0] icmp_ln1496_4_fu_2269_p2;
wire   [0:0] or_ln318_26_fu_2274_p2;
wire   [0:0] icmp_ln318_12_fu_2263_p2;
wire   [0:0] icmp_ln1498_18_fu_2297_p2;
wire   [0:0] icmp_ln1495_11_fu_2291_p2;
wire   [0:0] and_ln331_4_fu_2303_p2;
wire   [13:0] p_neg_11_fu_2315_p3;
wire   [13:0] sub_ln703_23_fu_2323_p2;
wire   [0:0] or_ln331_4_fu_2309_p2;
wire   [17:0] add_ln703_16_fu_2335_p2;
wire   [0:0] or_ln318_18_fu_2280_p2;
wire   [0:0] and_ln318_11_fu_2257_p2;
wire   [0:0] xor_ln318_4_fu_2347_p2;
wire   [0:0] or_ln318_27_fu_2353_p2;
wire   [13:0] sub_ln703_22_fu_2286_p2;
wire   [17:0] select_ln339_11_fu_2340_p3;
reg   [13:0] tmp_37_fu_2379_p4;
wire   [13:0] select_ln318_37_fu_2388_p3;
wire   [1:0] tmp_28_fu_2409_p4;
wire   [10:0] tmp_3_fu_2399_p4;
wire   [13:0] select_ln318_39_fu_2394_p3;
wire   [13:0] trunc_ln708_19_fu_2419_p4;
wire   [0:0] icmp_ln1498_12_fu_2441_p2;
wire   [0:0] icmp_ln1494_19_fu_2446_p2;
wire   [13:0] mul_FL_V_2_fu_2428_p3;
wire   [0:0] icmp_ln1494_12_fu_2436_p2;
wire   [0:0] icmp_ln1496_5_fu_2464_p2;
wire   [0:0] or_ln318_29_fu_2469_p2;
wire   [0:0] icmp_ln318_13_fu_2458_p2;
wire   [0:0] icmp_ln1498_19_fu_2492_p2;
wire   [0:0] icmp_ln1495_12_fu_2486_p2;
wire   [0:0] and_ln331_5_fu_2498_p2;
wire   [13:0] p_neg_12_fu_2510_p3;
wire   [13:0] sub_ln703_25_fu_2518_p2;
wire   [0:0] or_ln331_5_fu_2504_p2;
wire   [17:0] add_ln703_18_fu_2530_p2;
wire   [0:0] or_ln318_19_fu_2475_p2;
wire   [0:0] and_ln318_12_fu_2452_p2;
wire   [0:0] xor_ln318_5_fu_2552_p2;
wire   [0:0] or_ln318_30_fu_2558_p2;
wire   [0:0] or_ln318_31_fu_2564_p2;
reg   [13:0] tmp_38_fu_2542_p4;
wire   [13:0] sub_ln703_24_fu_2481_p2;
wire   [13:0] add_ln703_17_fu_2524_p2;
wire   [17:0] select_ln339_12_fu_2535_p3;
wire   [12:0] trunc_ln103_fu_2600_p1;
wire   [17:0] select_ln318_44_fu_2593_p3;
wire   [13:0] select_ln318_42_fu_2578_p3;
wire   [13:0] mul_FL_V_3_fu_2604_p3;
wire   [13:0] trunc_ln708_20_fu_2638_p4;
wire   [0:0] icmp_ln1494_20_fu_2646_p2;
wire   [0:0] or_ln318_32_fu_2661_p2;
wire   [0:0] icmp_ln318_14_fu_2656_p2;
wire   [0:0] or_ln318_20_fu_2665_p2;
wire   [0:0] and_ln318_13_fu_2651_p2;
wire   [0:0] xor_ln318_6_fu_2680_p2;
wire   [0:0] or_ln318_33_fu_2686_p2;
wire   [0:0] or_ln318_34_fu_2692_p2;
reg   [13:0] tmp_40_fu_2671_p4;
wire   [13:0] select_ln318_45_fu_2697_p3;
wire   [14:0] zext_ln1192_fu_2704_p1;
wire   [14:0] res_FH_l_V_fu_2708_p2;
wire   [0:0] p_Result_s_fu_2720_p3;
wire   [7:0] res_I_V_fu_2728_p2;
wire   [13:0] res_FH_V_fu_2714_p2;
wire   [7:0] p_Val2_s_fu_2733_p3;
wire   [12:0] tmp_30_fu_2740_p4;
wire   [20:0] r_V_fu_2750_p3;
reg    ap_ce_reg;
reg   [17:0] x_V_int_reg;
reg   [20:0] ap_return_int_reg;

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        add_ln703_15_reg_3168 <= add_ln703_15_fu_2329_p2;
        add_ln703_3_reg_2942 <= add_ln703_3_fu_953_p2;
        add_ln703_6_reg_3013 <= add_ln703_6_fu_1324_p2;
        add_ln703_reg_2789 <= add_ln703_fu_454_p2;
        icmp_ln1494_13_reg_3212 <= icmp_ln1494_13_fu_2620_p2;
        icmp_ln1494_3_reg_2927 <= icmp_ln1494_3_fu_935_p2;
        icmp_ln1495_3_reg_2937 <= icmp_ln1495_3_fu_947_p2;
        icmp_ln1495_6_reg_3008 <= icmp_ln1495_6_fu_1318_p2;
        icmp_ln1495_reg_2784 <= icmp_ln1495_fu_448_p2;
        icmp_ln1496_2_reg_3102 <= icmp_ln1496_2_fu_1842_p2;
        icmp_ln1496_6_reg_3223 <= icmp_ln1496_6_fu_2632_p2;
        icmp_ln1498_13_reg_3218 <= icmp_ln1498_13_fu_2626_p2;
        icmp_ln1498_3_reg_2932 <= icmp_ln1498_3_fu_941_p2;
        icmp_ln318_3_reg_2947 <= icmp_ln318_3_fu_959_p2;
        icmp_ln318_reg_2794 <= icmp_ln318_fu_470_p2;
        mul_FL_V_9_reg_3097[13 : 9] <= mul_FL_V_9_fu_1834_p3[13 : 9];
        or_ln318_10_reg_3036 <= or_ln318_10_fu_1575_p2;
        or_ln318_1_reg_2885 <= or_ln318_1_fu_743_p2;
        or_ln318_25_reg_3135 <= or_ln318_25_fu_2152_p2;
        or_ln318_28_reg_3173 <= or_ln318_28_fu_2359_p2;
        or_ln318_6_reg_3018 <= or_ln318_6_fu_1348_p2;
        p_Result_34_5_reg_2975 <= {{select_ln318_12_fu_1132_p3[13:8]}};
        p_neg_10_reg_3130 <= p_neg_10_fu_2118_p3;
        p_neg_9_reg_3108 <= p_neg_9_fu_1848_p3;
        select_ln318_12_reg_2952 <= select_ln318_12_fu_1132_p3;
        select_ln318_13_reg_2958[13 : 1] <= select_ln318_13_fu_1140_p3[13 : 1];
        select_ln318_14_reg_2966 <= select_ln318_14_fu_1148_p3;
        select_ln318_15_reg_2980 <= select_ln318_15_fu_1255_p3;
        select_ln318_16_reg_2986[13 : 1] <= select_ln318_16_fu_1262_p3[13 : 1];
        select_ln318_17_reg_2992 <= select_ln318_17_fu_1269_p3;
        select_ln318_18_reg_3025 <= select_ln318_18_fu_1377_p3;
        select_ln318_23_reg_3042 <= select_ln318_23_fu_1581_p3;
        select_ln318_24_reg_3052 <= select_ln318_24_fu_1589_p3;
        select_ln318_25_reg_3061 <= select_ln318_25_fu_1784_p3;
        select_ln318_26_reg_3067[13 : 10] <= select_ln318_26_fu_1792_p3[13 : 10];
        select_ln318_27_reg_3073 <= select_ln318_27_fu_1800_p3;
        select_ln318_28_reg_3083 <= select_ln318_28_fu_1807_p3;
        select_ln318_29_reg_3113 <= select_ln318_29_fu_1975_p3;
        select_ln318_2_reg_2875 <= select_ln318_2_fu_644_p3;
        select_ln318_31_reg_3119 <= select_ln318_31_fu_1989_p3;
        select_ln318_33_reg_3157 <= select_ln318_33_fu_2192_p3;
        select_ln318_34_reg_3141[13 : 6] <= select_ln318_34_fu_2158_p3[13 : 6];
        select_ln318_35_reg_3163 <= select_ln318_35_fu_2198_p3;
        select_ln318_36_reg_3148 <= select_ln318_36_fu_2166_p3;
        select_ln318_38_reg_3179[13 : 4] <= select_ln318_38_fu_2365_p3[13 : 4];
        select_ln318_40_reg_3186 <= select_ln318_40_fu_2372_p3;
        select_ln318_41_reg_3195 <= select_ln318_41_fu_2570_p3;
        select_ln318_43_reg_3201 <= select_ln318_43_fu_2585_p3;
        select_ln318_4_reg_2891[13 : 1] <= select_ln318_4_fu_749_p3[13 : 1];
        select_ln318_6_reg_2899 <= select_ln318_6_fu_882_p3;
        select_ln318_7_reg_2905[13 : 1] <= select_ln318_7_fu_890_p3[13 : 1];
        select_ln318_8_reg_2911 <= select_ln318_8_fu_897_p3;
        select_ln318_reg_2869[13] <= select_ln318_fu_628_p3[13];
        select_ln488_4_reg_2763 <= select_ln488_4_fu_422_p3;
        select_ln488_4_reg_2763_pp0_iter1_reg <= select_ln488_4_reg_2763;
        select_ln488_4_reg_2763_pp0_iter2_reg <= select_ln488_4_reg_2763_pp0_iter1_reg;
        select_ln488_4_reg_2763_pp0_iter3_reg <= select_ln488_4_reg_2763_pp0_iter2_reg;
        select_ln488_4_reg_2763_pp0_iter4_reg <= select_ln488_4_reg_2763_pp0_iter3_reg;
        select_ln488_4_reg_2763_pp0_iter5_reg <= select_ln488_4_reg_2763_pp0_iter4_reg;
        select_ln488_4_reg_2763_pp0_iter6_reg <= select_ln488_4_reg_2763_pp0_iter5_reg;
        select_ln488_4_reg_2763_pp0_iter7_reg <= select_ln488_4_reg_2763_pp0_iter6_reg;
        select_ln488_4_reg_2763_pp0_iter8_reg <= select_ln488_4_reg_2763_pp0_iter7_reg;
        select_ln488_4_reg_2763_pp0_iter9_reg <= select_ln488_4_reg_2763_pp0_iter8_reg;
        select_ln488_5_reg_2776 <= select_ln488_5_fu_430_p3;
        sub_ln703_13_reg_3031[13] <= sub_ln703_13_fu_1493_p2[13];
        sub_ln703_2_reg_2880 <= sub_ln703_2_fu_719_p2;
        tmp_11_reg_2809 <= {{select_ln488_4_fu_422_p3[7:2]}};
        tmp_11_reg_2809_pp0_iter1_reg <= tmp_11_reg_2809;
        tmp_13_reg_2819 <= {{select_ln488_4_fu_422_p3[7:3]}};
        tmp_13_reg_2819_pp0_iter1_reg <= tmp_13_reg_2819;
        tmp_15_reg_2829 <= {{select_ln488_4_fu_422_p3[7:4]}};
        tmp_15_reg_2829_pp0_iter1_reg <= tmp_15_reg_2829;
        tmp_15_reg_2829_pp0_iter2_reg <= tmp_15_reg_2829_pp0_iter1_reg;
        tmp_17_reg_2839 <= {{select_ln488_4_fu_422_p3[7:5]}};
        tmp_17_reg_2839_pp0_iter1_reg <= tmp_17_reg_2839;
        tmp_17_reg_2839_pp0_iter2_reg <= tmp_17_reg_2839_pp0_iter1_reg;
        tmp_17_reg_2839_pp0_iter3_reg <= tmp_17_reg_2839_pp0_iter2_reg;
        tmp_19_reg_2849 <= {{select_ln488_4_fu_422_p3[7:6]}};
        tmp_19_reg_2849_pp0_iter1_reg <= tmp_19_reg_2849;
        tmp_19_reg_2849_pp0_iter2_reg <= tmp_19_reg_2849_pp0_iter1_reg;
        tmp_19_reg_2849_pp0_iter3_reg <= tmp_19_reg_2849_pp0_iter2_reg;
        tmp_25_reg_3092 <= {{select_ln318_25_fu_1784_p3[13:9]}};
        tmp_32_reg_2859 <= select_ln488_4_fu_422_p3[32'd7];
        tmp_32_reg_2859_pp0_iter1_reg <= tmp_32_reg_2859;
        tmp_32_reg_2859_pp0_iter2_reg <= tmp_32_reg_2859_pp0_iter1_reg;
        tmp_32_reg_2859_pp0_iter3_reg <= tmp_32_reg_2859_pp0_iter2_reg;
        tmp_32_reg_2859_pp0_iter4_reg <= tmp_32_reg_2859_pp0_iter3_reg;
        tmp_39_reg_3207 <= select_ln318_41_fu_2570_p3[32'd13];
        tmp_5_reg_2799 <= {{select_ln488_4_fu_422_p3[7:1]}};
        trunc_ln708_12_reg_2998[13 : 1] <= trunc_ln708_12_fu_1293_p4[13 : 1];
        trunc_ln708_17_reg_3125[11 : 0] <= trunc_ln708_17_fu_2023_p4[11 : 0];
        trunc_ln708_21_reg_2814 <= trunc_ln708_21_fu_500_p1;
        trunc_ln708_21_reg_2814_pp0_iter1_reg <= trunc_ln708_21_reg_2814;
        trunc_ln708_22_reg_2824 <= trunc_ln708_22_fu_514_p1;
        trunc_ln708_22_reg_2824_pp0_iter1_reg <= trunc_ln708_22_reg_2824;
        trunc_ln708_23_reg_2834 <= trunc_ln708_23_fu_528_p1;
        trunc_ln708_23_reg_2834_pp0_iter1_reg <= trunc_ln708_23_reg_2834;
        trunc_ln708_23_reg_2834_pp0_iter2_reg <= trunc_ln708_23_reg_2834_pp0_iter1_reg;
        trunc_ln708_24_reg_2844 <= trunc_ln708_24_fu_542_p1;
        trunc_ln708_24_reg_2844_pp0_iter1_reg <= trunc_ln708_24_reg_2844;
        trunc_ln708_24_reg_2844_pp0_iter2_reg <= trunc_ln708_24_reg_2844_pp0_iter1_reg;
        trunc_ln708_24_reg_2844_pp0_iter3_reg <= trunc_ln708_24_reg_2844_pp0_iter2_reg;
        trunc_ln708_25_reg_2854 <= trunc_ln708_25_fu_556_p1;
        trunc_ln708_25_reg_2854_pp0_iter1_reg <= trunc_ln708_25_reg_2854;
        trunc_ln708_25_reg_2854_pp0_iter2_reg <= trunc_ln708_25_reg_2854_pp0_iter1_reg;
        trunc_ln708_25_reg_2854_pp0_iter3_reg <= trunc_ln708_25_reg_2854_pp0_iter2_reg;
        trunc_ln708_26_reg_2864 <= trunc_ln708_26_fu_568_p1;
        trunc_ln708_26_reg_2864_pp0_iter1_reg <= trunc_ln708_26_reg_2864;
        trunc_ln708_26_reg_2864_pp0_iter2_reg <= trunc_ln708_26_reg_2864_pp0_iter1_reg;
        trunc_ln708_26_reg_2864_pp0_iter3_reg <= trunc_ln708_26_reg_2864_pp0_iter2_reg;
        trunc_ln708_26_reg_2864_pp0_iter4_reg <= trunc_ln708_26_reg_2864_pp0_iter3_reg;
        trunc_ln708_8_reg_2917[13 : 7] <= trunc_ln708_8_fu_922_p4[13 : 7];
        trunc_ln708_reg_2804 <= trunc_ln708_fu_486_p1;
        trunc_ln731_reg_2758 <= trunc_ln731_fu_238_p1;
        zext_ln1494_3_reg_2922[4 : 0] <= zext_ln1494_3_fu_931_p1[4 : 0];
        zext_ln1494_6_reg_3003[1 : 0] <= zext_ln1494_6_fu_1302_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= r_V_fu_2750_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_V_int_reg <= x_V;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = r_V_fu_2750_p3;
    end
end

assign add_ln703_10_fu_1744_p2 = ($signed(select_ln318_24_reg_3052) + $signed(18'd262143));

assign add_ln703_11_fu_1931_p2 = (sub_ln703_19_fu_1926_p2 + select_ln318_27_reg_3073);

assign add_ln703_12_fu_1936_p2 = ($signed(select_ln318_28_reg_3083) + $signed(18'd262143));

assign add_ln703_13_fu_2178_p2 = (sub_ln703_21_fu_2174_p2 + select_ln318_31_reg_3119);

assign add_ln703_14_fu_2126_p2 = ($signed(select_ln318_32_fu_1996_p3) + $signed(18'd262143));

assign add_ln703_15_fu_2329_p2 = (sub_ln703_23_fu_2323_p2 + select_ln318_35_fu_2198_p3);

assign add_ln703_16_fu_2335_p2 = ($signed(select_ln318_36_reg_3148) + $signed(18'd262143));

assign add_ln703_17_fu_2524_p2 = (sub_ln703_25_fu_2518_p2 + select_ln318_39_fu_2394_p3);

assign add_ln703_18_fu_2530_p2 = ($signed(select_ln318_40_reg_3186) + $signed(18'd262143));

assign add_ln703_19_fu_600_p2 = ($signed(x_l_FH_V_fu_572_p3) + $signed(14'd12288));

assign add_ln703_1_fu_705_p2 = ($signed(select_ln318_2_fu_644_p3) + $signed(18'd262143));

assign add_ln703_2_fu_829_p2 = ($signed(select_ln318_5_fu_772_p3) + $signed(18'd262143));

assign add_ln703_3_fu_953_p2 = ($signed(select_ln318_8_fu_897_p3) + $signed(18'd262143));

assign add_ln703_4_fu_1078_p2 = ($signed(select_ln318_11_fu_1017_p3) + $signed(18'd262143));

assign add_ln703_5_fu_1205_p2 = ($signed(select_ln318_14_reg_2966) + $signed(18'd262143));

assign add_ln703_6_fu_1324_p2 = ($signed(select_ln318_17_fu_1269_p3) + $signed(18'd262143));

assign add_ln703_7_fu_1537_p2 = (sub_ln703_14_fu_1531_p2 + select_ln318_19_fu_1383_p3);

assign add_ln703_8_fu_1543_p2 = ($signed(select_ln318_20_fu_1389_p3) + $signed(18'd262143));

assign add_ln703_9_fu_1739_p2 = (sub_ln703_17_fu_1733_p2 + select_ln318_23_reg_3042);

assign add_ln703_fu_454_p2 = ($signed(select_ln488_5_fu_430_p3) + $signed(18'd262143));

assign and_ln318_10_fu_2058_p2 = (icmp_ln1498_10_fu_2046_p2 & icmp_ln1494_17_fu_2052_p2);

assign and_ln318_11_fu_2257_p2 = (icmp_ln1498_11_fu_2246_p2 & icmp_ln1494_18_fu_2251_p2);

assign and_ln318_12_fu_2452_p2 = (icmp_ln1498_12_fu_2441_p2 & icmp_ln1494_19_fu_2446_p2);

assign and_ln318_13_fu_2651_p2 = (icmp_ln1498_13_reg_3218 & icmp_ln1494_20_fu_2646_p2);

assign and_ln318_1_fu_737_p2 = (xor_ln318_7_fu_731_p2 & icmp_ln1498_1_fu_687_p2);

assign and_ln318_2_fu_870_p2 = (xor_ln318_8_fu_864_p2 & icmp_ln1498_2_fu_813_p2);

assign and_ln318_3_fu_993_p2 = (xor_ln318_9_fu_988_p2 & icmp_ln1498_3_reg_2932);

assign and_ln318_4_fu_1120_p2 = (xor_ln318_10_fu_1114_p2 & icmp_ln1498_4_fu_1060_p2);

assign and_ln318_5_fu_1243_p2 = (xor_ln318_11_fu_1237_p2 & icmp_ln1498_5_fu_1190_p2);

assign and_ln318_6_fu_1342_p2 = (xor_ln318_12_fu_1336_p2 & icmp_ln1498_6_fu_1312_p2);

assign and_ln318_7_fu_1457_p2 = (icmp_ln1498_7_fu_1445_p2 & icmp_ln1494_14_fu_1451_p2);

assign and_ln318_8_fu_1668_p2 = (icmp_ln1498_8_fu_1658_p2 & icmp_ln1494_15_fu_1663_p2);

assign and_ln318_9_fu_1879_p2 = (icmp_ln1498_9_fu_1869_p2 & icmp_ln1494_16_fu_1874_p2);

assign and_ln318_fu_617_p2 = (icmp_ln318_reg_2794 & icmp_ln1498_fu_595_p2);

assign and_ln331_1_fu_1713_p2 = (icmp_ln1498_15_fu_1708_p2 & icmp_ln1496_1_fu_1679_p2);

assign and_ln331_2_fu_1915_p2 = (icmp_ln1498_16_fu_1910_p2 & icmp_ln1496_2_reg_3102);

assign and_ln331_3_fu_2106_p2 = (icmp_ln1498_17_fu_2100_p2 & icmp_ln1496_3_fu_2070_p2);

assign and_ln331_4_fu_2303_p2 = (icmp_ln1498_18_fu_2297_p2 & icmp_ln1496_4_fu_2269_p2);

assign and_ln331_5_fu_2498_p2 = (icmp_ln1498_19_fu_2492_p2 & icmp_ln1496_5_fu_2464_p2);

assign and_ln331_fu_1511_p2 = (icmp_ln1498_14_fu_1505_p2 & icmp_ln1496_fu_1475_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign icmp_ln1494_10_fu_2040_p2 = ((select_ln318_32_fu_1996_p3 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_11_fu_2241_p2 = ((select_ln318_36_reg_3148 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_12_fu_2436_p2 = ((select_ln318_40_reg_3186 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_13_fu_2620_p2 = ((select_ln318_44_fu_2593_p3 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_14_fu_1451_p2 = ((select_ln318_19_fu_1383_p3 > trunc_ln708_14_fu_1420_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_15_fu_1663_p2 = ((select_ln318_23_reg_3042 > trunc_ln708_15_fu_1638_p3) ? 1'b1 : 1'b0);

assign icmp_ln1494_16_fu_1874_p2 = ((select_ln318_27_reg_3073 > trunc_ln708_16_fu_1856_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_17_fu_2052_p2 = ((select_ln318_31_fu_1989_p3 > trunc_ln708_17_fu_2023_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_18_fu_2251_p2 = ((select_ln318_35_fu_2198_p3 > trunc_ln708_18_fu_2224_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_19_fu_2446_p2 = ((select_ln318_39_fu_2394_p3 > trunc_ln708_19_fu_2419_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_1_fu_681_p2 = ((select_ln318_2_fu_644_p3 > zext_ln1494_1_fu_677_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_20_fu_2646_p2 = ((select_ln318_43_reg_3201 > trunc_ln708_20_fu_2638_p4) ? 1'b1 : 1'b0);

assign icmp_ln1494_2_fu_807_p2 = ((select_ln318_5_fu_772_p3 > zext_ln1494_2_fu_803_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_3_fu_935_p2 = ((select_ln318_8_fu_897_p3 > zext_ln1494_3_fu_931_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_4_fu_1054_p2 = ((select_ln318_11_fu_1017_p3 > zext_ln1494_4_fu_1050_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_5_fu_1185_p2 = ((select_ln318_14_reg_2966 > zext_ln1494_5_fu_1181_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_6_fu_1306_p2 = ((select_ln318_17_fu_1269_p3 > zext_ln1494_6_fu_1302_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_7_fu_1439_p2 = ((select_ln318_20_fu_1389_p3 > zext_ln1494_7_fu_1435_p1) ? 1'b1 : 1'b0);

assign icmp_ln1494_8_fu_1653_p2 = ((select_ln318_24_reg_3052 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_9_fu_1864_p2 = ((select_ln318_28_reg_3083 != 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1494_fu_590_p2 = ((select_ln488_5_reg_2776 > zext_ln1494_fu_586_p1) ? 1'b1 : 1'b0);

assign icmp_ln1495_10_fu_2094_p2 = ((select_ln318_31_fu_1989_p3 < trunc_ln708_17_fu_2023_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_11_fu_2291_p2 = ((select_ln318_35_fu_2198_p3 < trunc_ln708_18_fu_2224_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_12_fu_2486_p2 = ((select_ln318_39_fu_2394_p3 < trunc_ln708_19_fu_2419_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_1_fu_693_p2 = ((select_ln318_1_fu_636_p3 < trunc_ln708_4_fu_668_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_2_fu_819_p2 = ((select_ln318_4_reg_2891 < trunc_ln708_6_fu_794_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_3_fu_947_p2 = ((select_ln318_7_fu_890_p3 < trunc_ln708_8_fu_922_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_4_fu_1066_p2 = ((select_ln318_10_fu_1010_p3 < trunc_ln708_s_fu_1041_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_5_fu_1195_p2 = ((select_ln318_13_reg_2958 < trunc_ln708_10_fu_1173_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_6_fu_1318_p2 = ((select_ln318_16_fu_1262_p3 < trunc_ln708_12_fu_1293_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_7_fu_1499_p2 = ((select_ln318_19_fu_1383_p3 < trunc_ln708_14_fu_1420_p3) ? 1'b1 : 1'b0);

assign icmp_ln1495_8_fu_1703_p2 = ((select_ln318_23_reg_3042 < trunc_ln708_15_fu_1638_p3) ? 1'b1 : 1'b0);

assign icmp_ln1495_9_fu_1905_p2 = ((select_ln318_27_reg_3073 < trunc_ln708_16_fu_1856_p4) ? 1'b1 : 1'b0);

assign icmp_ln1495_fu_448_p2 = ((tmp_12_fu_438_p4 == 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln1496_1_fu_1679_p2 = ((select_ln318_22_fu_1612_p3 < mul_FL_V_8_fu_1645_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_2_fu_1842_p2 = ((select_ln318_26_fu_1792_p3 < mul_FL_V_9_fu_1834_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_3_fu_2070_p2 = ((select_ln318_30_fu_1982_p3 < mul_FL_V_s_fu_2032_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_4_fu_2269_p2 = ((select_ln318_34_reg_3141 < mul_FL_V_1_fu_2233_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_5_fu_2464_p2 = ((select_ln318_38_reg_3179 < mul_FL_V_2_fu_2428_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_6_fu_2632_p2 = ((select_ln318_42_fu_2578_p3 < mul_FL_V_3_fu_2604_p3) ? 1'b1 : 1'b0);

assign icmp_ln1496_fu_1475_p2 = ((mul_FL_V_7_fu_1427_p3 != 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_10_fu_2046_p2 = ((select_ln318_32_fu_1996_p3 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_11_fu_2246_p2 = ((select_ln318_36_reg_3148 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_12_fu_2441_p2 = ((select_ln318_40_reg_3186 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_13_fu_2626_p2 = ((select_ln318_44_fu_2593_p3 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_14_fu_1505_p2 = ((select_ln318_19_fu_1383_p3 == trunc_ln708_14_fu_1420_p3) ? 1'b1 : 1'b0);

assign icmp_ln1498_15_fu_1708_p2 = ((select_ln318_23_reg_3042 == trunc_ln708_15_fu_1638_p3) ? 1'b1 : 1'b0);

assign icmp_ln1498_16_fu_1910_p2 = ((select_ln318_27_reg_3073 == trunc_ln708_16_fu_1856_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_17_fu_2100_p2 = ((select_ln318_31_fu_1989_p3 == trunc_ln708_17_fu_2023_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_18_fu_2297_p2 = ((select_ln318_35_fu_2198_p3 == trunc_ln708_18_fu_2224_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_19_fu_2492_p2 = ((select_ln318_39_fu_2394_p3 == trunc_ln708_19_fu_2419_p4) ? 1'b1 : 1'b0);

assign icmp_ln1498_1_fu_687_p2 = ((select_ln318_2_fu_644_p3 == zext_ln1494_1_fu_677_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_2_fu_813_p2 = ((select_ln318_5_fu_772_p3 == zext_ln1494_2_fu_803_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_3_fu_941_p2 = ((select_ln318_8_fu_897_p3 == zext_ln1494_3_fu_931_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_4_fu_1060_p2 = ((select_ln318_11_fu_1017_p3 == zext_ln1494_4_fu_1050_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_5_fu_1190_p2 = ((select_ln318_14_reg_2966 == zext_ln1494_5_fu_1181_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_6_fu_1312_p2 = ((select_ln318_17_fu_1269_p3 == zext_ln1494_6_fu_1302_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_7_fu_1445_p2 = ((select_ln318_20_fu_1389_p3 == zext_ln1494_7_fu_1435_p1) ? 1'b1 : 1'b0);

assign icmp_ln1498_8_fu_1658_p2 = ((select_ln318_24_reg_3052 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_9_fu_1869_p2 = ((select_ln318_28_reg_3083 == 18'd0) ? 1'b1 : 1'b0);

assign icmp_ln1498_fu_595_p2 = ((select_ln488_5_reg_2776 == zext_ln1494_fu_586_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_10_fu_1885_p2 = ((select_ln318_27_reg_3073 != trunc_ln708_16_fu_1856_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_11_fu_2064_p2 = ((select_ln318_31_fu_1989_p3 != trunc_ln708_17_fu_2023_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_12_fu_2263_p2 = ((select_ln318_35_fu_2198_p3 != trunc_ln708_18_fu_2224_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_13_fu_2458_p2 = ((select_ln318_39_fu_2394_p3 != trunc_ln708_19_fu_2419_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_14_fu_2656_p2 = ((select_ln318_43_reg_3201 != trunc_ln708_20_fu_2638_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_1_fu_725_p2 = ((select_ln318_1_fu_636_p3 < trunc_ln708_4_fu_668_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_2_fu_859_p2 = ((select_ln318_4_reg_2891 < trunc_ln708_6_fu_794_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_3_fu_959_p2 = ((select_ln318_7_fu_890_p3 < trunc_ln708_8_fu_922_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_4_fu_1108_p2 = ((select_ln318_10_fu_1010_p3 < trunc_ln708_s_fu_1041_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_5_fu_1232_p2 = ((select_ln318_13_reg_2958 < trunc_ln708_10_fu_1173_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_6_fu_1330_p2 = ((select_ln318_16_fu_1262_p3 < trunc_ln708_12_fu_1293_p4) ? 1'b1 : 1'b0);

assign icmp_ln318_7_fu_1463_p2 = ((select_ln318_20_fu_1389_p3 != zext_ln1494_7_fu_1435_p1) ? 1'b1 : 1'b0);

assign icmp_ln318_8_fu_1469_p2 = ((select_ln318_19_fu_1383_p3 != trunc_ln708_14_fu_1420_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_9_fu_1674_p2 = ((select_ln318_23_reg_3042 != trunc_ln708_15_fu_1638_p3) ? 1'b1 : 1'b0);

assign icmp_ln318_fu_470_p2 = ((tmp_14_fu_460_p4 != 2'd0) ? 1'b1 : 1'b0);

assign icmp_ln488_1_fu_388_p2 = ((trunc_ln612_fu_380_p1 < zext_ln488_1_fu_384_p1) ? 1'b1 : 1'b0);

assign icmp_ln488_fu_322_p2 = ((p_Result_28_6_fu_308_p4 < zext_ln488_fu_318_p1) ? 1'b1 : 1'b0);

assign mul_FL_V_1_fu_2233_p3 = {{tmp_2_fu_2204_p4}, {5'd16}};

assign mul_FL_V_2_fu_2428_p3 = {{tmp_3_fu_2399_p4}, {3'd4}};

assign mul_FL_V_3_fu_2604_p3 = {{trunc_ln103_fu_2600_p1}, {1'd1}};

assign mul_FL_V_7_fu_1427_p3 = {{tmp_31_fu_1395_p3}, {13'd4096}};

assign mul_FL_V_8_fu_1645_p3 = {{tmp_9_fu_1618_p4}, {11'd1024}};

assign mul_FL_V_9_fu_1834_p3 = {{tmp_s_fu_1814_p4}, {9'd256}};

assign mul_FL_V_s_fu_2032_p3 = {{tmp_1_fu_2003_p4}, {7'd64}};

assign or_ln318_10_fu_1575_p2 = (or_ln318_9_fu_1569_p2 | icmp_ln1494_7_fu_1439_p2);

assign or_ln318_11_fu_1685_p2 = (icmp_ln1496_1_fu_1679_p2 | icmp_ln1494_8_fu_1653_p2);

assign or_ln318_12_fu_1691_p2 = (or_ln318_11_fu_1685_p2 | icmp_ln318_9_fu_1674_p2);

assign or_ln318_13_fu_1772_p2 = (xor_ln318_1_fu_1766_p2 | and_ln318_8_fu_1668_p2);

assign or_ln318_14_fu_1778_p2 = (or_ln318_13_fu_1772_p2 | icmp_ln1494_8_fu_1653_p2);

assign or_ln318_15_fu_1890_p2 = (icmp_ln1496_2_reg_3102 | icmp_ln1494_9_fu_1864_p2);

assign or_ln318_16_fu_1895_p2 = (or_ln318_15_fu_1890_p2 | icmp_ln318_10_fu_1885_p2);

assign or_ln318_17_fu_2082_p2 = (or_ln318_23_fu_2076_p2 | icmp_ln318_11_fu_2064_p2);

assign or_ln318_18_fu_2280_p2 = (or_ln318_26_fu_2274_p2 | icmp_ln318_12_fu_2263_p2);

assign or_ln318_19_fu_2475_p2 = (or_ln318_29_fu_2469_p2 | icmp_ln318_13_fu_2458_p2);

assign or_ln318_1_fu_743_p2 = (icmp_ln1494_1_fu_681_p2 | and_ln318_1_fu_737_p2);

assign or_ln318_20_fu_2665_p2 = (or_ln318_32_fu_2661_p2 | icmp_ln318_14_fu_2656_p2);

assign or_ln318_21_fu_1963_p2 = (xor_ln318_2_fu_1957_p2 | and_ln318_9_fu_1879_p2);

assign or_ln318_22_fu_1969_p2 = (or_ln318_21_fu_1963_p2 | icmp_ln1494_9_fu_1864_p2);

assign or_ln318_23_fu_2076_p2 = (icmp_ln1496_3_fu_2070_p2 | icmp_ln1494_10_fu_2040_p2);

assign or_ln318_24_fu_2146_p2 = (xor_ln318_3_fu_2140_p2 | and_ln318_10_fu_2058_p2);

assign or_ln318_25_fu_2152_p2 = (or_ln318_24_fu_2146_p2 | icmp_ln1494_10_fu_2040_p2);

assign or_ln318_26_fu_2274_p2 = (icmp_ln1496_4_fu_2269_p2 | icmp_ln1494_11_fu_2241_p2);

assign or_ln318_27_fu_2353_p2 = (xor_ln318_4_fu_2347_p2 | and_ln318_11_fu_2257_p2);

assign or_ln318_28_fu_2359_p2 = (or_ln318_27_fu_2353_p2 | icmp_ln1494_11_fu_2241_p2);

assign or_ln318_29_fu_2469_p2 = (icmp_ln1496_5_fu_2464_p2 | icmp_ln1494_12_fu_2436_p2);

assign or_ln318_2_fu_876_p2 = (icmp_ln1494_2_fu_807_p2 | and_ln318_2_fu_870_p2);

assign or_ln318_30_fu_2558_p2 = (xor_ln318_5_fu_2552_p2 | and_ln318_12_fu_2452_p2);

assign or_ln318_31_fu_2564_p2 = (or_ln318_30_fu_2558_p2 | icmp_ln1494_12_fu_2436_p2);

assign or_ln318_32_fu_2661_p2 = (icmp_ln1496_6_reg_3223 | icmp_ln1494_13_reg_3212);

assign or_ln318_33_fu_2686_p2 = (xor_ln318_6_fu_2680_p2 | and_ln318_13_fu_2651_p2);

assign or_ln318_34_fu_2692_p2 = (or_ln318_33_fu_2686_p2 | icmp_ln1494_13_reg_3212);

assign or_ln318_3_fu_998_p2 = (icmp_ln1494_3_reg_2927 | and_ln318_3_fu_993_p2);

assign or_ln318_4_fu_1126_p2 = (icmp_ln1494_4_fu_1054_p2 | and_ln318_4_fu_1120_p2);

assign or_ln318_5_fu_1249_p2 = (icmp_ln1494_5_fu_1185_p2 | and_ln318_5_fu_1243_p2);

assign or_ln318_6_fu_1348_p2 = (icmp_ln1494_6_fu_1306_p2 | and_ln318_6_fu_1342_p2);

assign or_ln318_7_fu_1481_p2 = (icmp_ln318_7_fu_1463_p2 | icmp_ln1496_fu_1475_p2);

assign or_ln318_8_fu_1487_p2 = (or_ln318_7_fu_1481_p2 | icmp_ln318_8_fu_1469_p2);

assign or_ln318_9_fu_1569_p2 = (xor_ln318_fu_1563_p2 | and_ln318_7_fu_1457_p2);

assign or_ln318_fu_622_p2 = (icmp_ln1494_fu_590_p2 | and_ln318_fu_617_p2);

assign or_ln331_1_fu_1719_p2 = (icmp_ln1495_8_fu_1703_p2 | and_ln331_1_fu_1713_p2);

assign or_ln331_2_fu_1920_p2 = (icmp_ln1495_9_fu_1905_p2 | and_ln331_2_fu_1915_p2);

assign or_ln331_3_fu_2112_p2 = (icmp_ln1495_10_fu_2094_p2 | and_ln331_3_fu_2106_p2);

assign or_ln331_4_fu_2309_p2 = (icmp_ln1495_11_fu_2291_p2 | and_ln331_4_fu_2303_p2);

assign or_ln331_5_fu_2504_p2 = (icmp_ln1495_12_fu_2486_p2 | and_ln331_5_fu_2498_p2);

assign or_ln331_fu_1517_p2 = (icmp_ln1495_7_fu_1499_p2 | and_ln331_fu_1511_p2);

assign p_Result_28_6_fu_308_p4 = {{select_ln488_1_fu_284_p3[10:2]}};

assign p_Result_30_5_fu_264_p5 = {{x_l_I_V_fu_234_p1[17:12]}, {select_ln248_fu_256_p3}, {x_l_I_V_fu_234_p1[3:0]}};

assign p_Result_30_6_fu_334_p5 = {{select_ln488_1_fu_284_p3[17:11]}, {sub_ln248_fu_328_p2}, {select_ln488_1_fu_284_p3[1:0]}};

assign p_Result_30_7_fu_400_p5 = {{select_ln488_3_fu_364_p3[17:10]}, {sub_ln248_1_fu_394_p2}};

assign p_Result_34_1_fu_651_p4 = {{select_ln318_fu_628_p3[13:12]}};

assign p_Result_34_2_fu_777_p4 = {{select_ln318_3_fu_766_p3[13:11]}};

assign p_Result_34_3_fu_905_p4 = {{select_ln318_6_fu_882_p3[13:10]}};

assign p_Result_34_4_fu_1024_p4 = {{select_ln318_9_fu_1003_p3[13:9]}};

assign p_Result_34_6_fu_1276_p4 = {{select_ln318_15_fu_1255_p3[13:7]}};

assign p_Result_s_fu_2720_p3 = res_FH_l_V_fu_2708_p2[32'd14];

assign p_Val2_s_fu_2733_p3 = ((p_Result_s_fu_2720_p3[0:0] === 1'b1) ? res_I_V_fu_2728_p2 : select_ln488_4_reg_2763_pp0_iter9_reg);

assign p_neg_10_fu_2118_p3 = ((icmp_ln1496_3_fu_2070_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign p_neg_11_fu_2315_p3 = ((icmp_ln1496_4_fu_2269_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign p_neg_12_fu_2510_p3 = ((icmp_ln1496_5_fu_2464_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign p_neg_7_fu_1523_p3 = ((icmp_ln1496_fu_1475_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign p_neg_8_fu_1725_p3 = ((icmp_ln1496_1_fu_1679_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign p_neg_9_fu_1848_p3 = ((icmp_ln1496_2_fu_1842_p2[0:0] === 1'b1) ? 14'd16383 : 14'd0);

assign r_V_fu_2750_p3 = {{p_Val2_s_fu_2733_p3}, {tmp_30_fu_2740_p4}};

assign res_FH_V_fu_2714_p2 = (select_ln318_45_fu_2697_p3 + 14'd1);

assign res_FH_l_V_fu_2708_p2 = (zext_ln1192_fu_2704_p1 + 15'd1);

assign res_I_V_fu_2728_p2 = (select_ln488_4_reg_2763_pp0_iter9_reg + 8'd1);

assign select_ln248_fu_256_p3 = ((xor_ln248_fu_250_p2[0:0] === 1'b1) ? 8'd255 : 8'd0);

assign select_ln318_10_fu_1010_p3 = ((or_ln318_3_fu_998_p2[0:0] === 1'b1) ? sub_ln703_5_fu_965_p2 : select_ln318_7_reg_2905);

assign select_ln318_11_fu_1017_p3 = ((or_ln318_3_fu_998_p2[0:0] === 1'b1) ? sub_ln703_6_fu_974_p2 : select_ln318_8_reg_2911);

assign select_ln318_12_fu_1132_p3 = ((or_ln318_4_fu_1126_p2[0:0] === 1'b1) ? tmp_21_fu_1098_p4 : select_ln318_9_fu_1003_p3);

assign select_ln318_13_fu_1140_p3 = ((or_ln318_4_fu_1126_p2[0:0] === 1'b1) ? sub_ln703_7_fu_1072_p2 : select_ln318_10_fu_1010_p3);

assign select_ln318_14_fu_1148_p3 = ((or_ln318_4_fu_1126_p2[0:0] === 1'b1) ? sub_ln703_8_fu_1092_p2 : select_ln318_11_fu_1017_p3);

assign select_ln318_15_fu_1255_p3 = ((or_ln318_5_fu_1249_p2[0:0] === 1'b1) ? tmp_23_fu_1223_p4 : select_ln318_12_reg_2952);

assign select_ln318_16_fu_1262_p3 = ((or_ln318_5_fu_1249_p2[0:0] === 1'b1) ? sub_ln703_9_fu_1200_p2 : select_ln318_13_reg_2958);

assign select_ln318_17_fu_1269_p3 = ((or_ln318_5_fu_1249_p2[0:0] === 1'b1) ? sub_ln703_10_fu_1217_p2 : select_ln318_14_reg_2966);

assign select_ln318_18_fu_1377_p3 = ((or_ln318_6_reg_3018[0:0] === 1'b1) ? tmp_29_fu_1368_p4 : select_ln318_15_reg_2980);

assign select_ln318_19_fu_1383_p3 = ((or_ln318_6_reg_3018[0:0] === 1'b1) ? sub_ln703_11_fu_1354_p2 : select_ln318_16_reg_2986);

assign select_ln318_1_fu_636_p3 = ((or_ln318_fu_622_p2[0:0] === 1'b1) ? add_ln703_19_fu_600_p2 : x_l_FH_V_fu_572_p3);

assign select_ln318_20_fu_1389_p3 = ((or_ln318_6_reg_3018[0:0] === 1'b1) ? sub_ln703_12_fu_1363_p2 : select_ln318_17_reg_2992);

assign select_ln318_21_fu_1606_p3 = ((or_ln318_10_reg_3036[0:0] === 1'b1) ? tmp_33_fu_1597_p4 : select_ln318_18_reg_3025);

assign select_ln318_22_fu_1612_p3 = ((or_ln318_10_reg_3036[0:0] === 1'b1) ? sub_ln703_13_reg_3031 : 14'd0);

assign select_ln318_23_fu_1581_p3 = ((or_ln318_10_fu_1575_p2[0:0] === 1'b1) ? add_ln703_7_fu_1537_p2 : select_ln318_19_fu_1383_p3);

assign select_ln318_24_fu_1589_p3 = ((or_ln318_10_fu_1575_p2[0:0] === 1'b1) ? sub_ln703_15_fu_1557_p2 : select_ln318_20_fu_1389_p3);

assign select_ln318_25_fu_1784_p3 = ((or_ln318_14_fu_1778_p2[0:0] === 1'b1) ? tmp_34_fu_1756_p4 : select_ln318_21_fu_1606_p3);

assign select_ln318_26_fu_1792_p3 = ((or_ln318_14_fu_1778_p2[0:0] === 1'b1) ? sub_ln703_16_fu_1697_p2 : select_ln318_22_fu_1612_p3);

assign select_ln318_27_fu_1800_p3 = ((or_ln318_14_fu_1778_p2[0:0] === 1'b1) ? add_ln703_9_fu_1739_p2 : select_ln318_23_reg_3042);

assign select_ln318_28_fu_1807_p3 = ((or_ln318_14_fu_1778_p2[0:0] === 1'b1) ? select_ln339_8_fu_1749_p3 : select_ln318_24_reg_3052);

assign select_ln318_29_fu_1975_p3 = ((or_ln318_22_fu_1969_p2[0:0] === 1'b1) ? tmp_35_fu_1948_p4 : select_ln318_25_reg_3061);

assign select_ln318_2_fu_644_p3 = ((or_ln318_fu_622_p2[0:0] === 1'b1) ? sub_ln703_fu_611_p2 : select_ln488_5_reg_2776);

assign select_ln318_30_fu_1982_p3 = ((or_ln318_22_fu_1969_p2[0:0] === 1'b1) ? sub_ln703_18_fu_1901_p2 : select_ln318_26_reg_3067);

assign select_ln318_31_fu_1989_p3 = ((or_ln318_22_fu_1969_p2[0:0] === 1'b1) ? add_ln703_11_fu_1931_p2 : select_ln318_27_reg_3073);

assign select_ln318_32_fu_1996_p3 = ((or_ln318_22_fu_1969_p2[0:0] === 1'b1) ? select_ln339_9_fu_1941_p3 : select_ln318_28_reg_3083);

assign select_ln318_33_fu_2192_p3 = ((or_ln318_25_reg_3135[0:0] === 1'b1) ? tmp_36_fu_2183_p4 : select_ln318_29_reg_3113);

assign select_ln318_34_fu_2158_p3 = ((or_ln318_25_fu_2152_p2[0:0] === 1'b1) ? sub_ln703_20_fu_2088_p2 : select_ln318_30_fu_1982_p3);

assign select_ln318_35_fu_2198_p3 = ((or_ln318_25_reg_3135[0:0] === 1'b1) ? add_ln703_13_fu_2178_p2 : select_ln318_31_reg_3119);

assign select_ln318_36_fu_2166_p3 = ((or_ln318_25_fu_2152_p2[0:0] === 1'b1) ? select_ln339_10_fu_2132_p3 : select_ln318_32_fu_1996_p3);

assign select_ln318_37_fu_2388_p3 = ((or_ln318_28_reg_3173[0:0] === 1'b1) ? tmp_37_fu_2379_p4 : select_ln318_33_reg_3157);

assign select_ln318_38_fu_2365_p3 = ((or_ln318_28_fu_2359_p2[0:0] === 1'b1) ? sub_ln703_22_fu_2286_p2 : select_ln318_34_reg_3141);

assign select_ln318_39_fu_2394_p3 = ((or_ln318_28_reg_3173[0:0] === 1'b1) ? add_ln703_15_reg_3168 : select_ln318_35_reg_3163);

assign select_ln318_3_fu_766_p3 = ((or_ln318_1_reg_2885[0:0] === 1'b1) ? tmp_16_fu_757_p4 : select_ln318_reg_2869);

assign select_ln318_40_fu_2372_p3 = ((or_ln318_28_fu_2359_p2[0:0] === 1'b1) ? select_ln339_11_fu_2340_p3 : select_ln318_36_reg_3148);

assign select_ln318_41_fu_2570_p3 = ((or_ln318_31_fu_2564_p2[0:0] === 1'b1) ? tmp_38_fu_2542_p4 : select_ln318_37_fu_2388_p3);

assign select_ln318_42_fu_2578_p3 = ((or_ln318_31_fu_2564_p2[0:0] === 1'b1) ? sub_ln703_24_fu_2481_p2 : select_ln318_38_reg_3179);

assign select_ln318_43_fu_2585_p3 = ((or_ln318_31_fu_2564_p2[0:0] === 1'b1) ? add_ln703_17_fu_2524_p2 : select_ln318_39_fu_2394_p3);

assign select_ln318_44_fu_2593_p3 = ((or_ln318_31_fu_2564_p2[0:0] === 1'b1) ? select_ln339_12_fu_2535_p3 : select_ln318_40_reg_3186);

assign select_ln318_45_fu_2697_p3 = ((or_ln318_34_fu_2692_p2[0:0] === 1'b1) ? tmp_40_fu_2671_p4 : select_ln318_41_reg_3195);

assign select_ln318_4_fu_749_p3 = ((or_ln318_1_fu_743_p2[0:0] === 1'b1) ? sub_ln703_1_fu_699_p2 : select_ln318_1_fu_636_p3);

assign select_ln318_5_fu_772_p3 = ((or_ln318_1_reg_2885[0:0] === 1'b1) ? sub_ln703_2_reg_2880 : select_ln318_2_reg_2875);

assign select_ln318_6_fu_882_p3 = ((or_ln318_2_fu_876_p2[0:0] === 1'b1) ? tmp_18_fu_849_p4 : select_ln318_3_fu_766_p3);

assign select_ln318_7_fu_890_p3 = ((or_ln318_2_fu_876_p2[0:0] === 1'b1) ? sub_ln703_3_fu_824_p2 : select_ln318_4_reg_2891);

assign select_ln318_8_fu_897_p3 = ((or_ln318_2_fu_876_p2[0:0] === 1'b1) ? sub_ln703_4_fu_843_p2 : select_ln318_5_fu_772_p3);

assign select_ln318_9_fu_1003_p3 = ((or_ln318_3_fu_998_p2[0:0] === 1'b1) ? tmp_20_fu_979_p4 : select_ln318_6_reg_2899);

assign select_ln318_fu_628_p3 = ((or_ln318_fu_622_p2[0:0] === 1'b1) ? 14'd8192 : 14'd0);

assign select_ln339_10_fu_2132_p3 = ((or_ln331_3_fu_2112_p2[0:0] === 1'b1) ? add_ln703_14_fu_2126_p2 : select_ln318_32_fu_1996_p3);

assign select_ln339_11_fu_2340_p3 = ((or_ln331_4_fu_2309_p2[0:0] === 1'b1) ? add_ln703_16_fu_2335_p2 : select_ln318_36_reg_3148);

assign select_ln339_12_fu_2535_p3 = ((or_ln331_5_fu_2504_p2[0:0] === 1'b1) ? add_ln703_18_fu_2530_p2 : select_ln318_40_reg_3186);

assign select_ln339_1_fu_711_p3 = ((icmp_ln1495_1_fu_693_p2[0:0] === 1'b1) ? add_ln703_1_fu_705_p2 : select_ln318_2_fu_644_p3);

assign select_ln339_2_fu_835_p3 = ((icmp_ln1495_2_fu_819_p2[0:0] === 1'b1) ? add_ln703_2_fu_829_p2 : select_ln318_5_fu_772_p3);

assign select_ln339_3_fu_969_p3 = ((icmp_ln1495_3_reg_2937[0:0] === 1'b1) ? add_ln703_3_reg_2942 : select_ln318_8_reg_2911);

assign select_ln339_4_fu_1084_p3 = ((icmp_ln1495_4_fu_1066_p2[0:0] === 1'b1) ? add_ln703_4_fu_1078_p2 : select_ln318_11_fu_1017_p3);

assign select_ln339_5_fu_1210_p3 = ((icmp_ln1495_5_fu_1195_p2[0:0] === 1'b1) ? add_ln703_5_fu_1205_p2 : select_ln318_14_reg_2966);

assign select_ln339_6_fu_1358_p3 = ((icmp_ln1495_6_reg_3008[0:0] === 1'b1) ? add_ln703_6_reg_3013 : select_ln318_17_reg_2992);

assign select_ln339_7_fu_1549_p3 = ((or_ln331_fu_1517_p2[0:0] === 1'b1) ? add_ln703_8_fu_1543_p2 : select_ln318_20_fu_1389_p3);

assign select_ln339_8_fu_1749_p3 = ((or_ln331_1_fu_1719_p2[0:0] === 1'b1) ? add_ln703_10_fu_1744_p2 : select_ln318_24_reg_3052);

assign select_ln339_9_fu_1941_p3 = ((or_ln331_2_fu_1920_p2[0:0] === 1'b1) ? add_ln703_12_fu_1936_p2 : select_ln318_28_reg_3083);

assign select_ln339_fu_606_p3 = ((icmp_ln1495_reg_2784[0:0] === 1'b1) ? add_ln703_reg_2789 : select_ln488_5_reg_2776);

assign select_ln488_1_fu_284_p3 = ((tmp_4_fu_242_p3[0:0] === 1'b1) ? p_Result_30_5_fu_264_p5 : x_l_I_V_fu_234_p1);

assign select_ln488_2_fu_356_p3 = ((icmp_ln488_fu_322_p2[0:0] === 1'b1) ? select_ln488_fu_276_p3 : tmp_8_fu_346_p4);

assign select_ln488_3_fu_364_p3 = ((icmp_ln488_fu_322_p2[0:0] === 1'b1) ? select_ln488_1_fu_284_p3 : p_Result_30_6_fu_334_p5);

assign select_ln488_4_fu_422_p3 = ((icmp_ln488_1_fu_388_p2[0:0] === 1'b1) ? select_ln488_2_fu_356_p3 : tmp_10_fu_412_p4);

assign select_ln488_5_fu_430_p3 = ((icmp_ln488_1_fu_388_p2[0:0] === 1'b1) ? select_ln488_3_fu_364_p3 : p_Result_30_7_fu_400_p5);

assign select_ln488_6_fu_292_p3 = ((tmp_4_fu_242_p3[0:0] === 1'b1) ? 2'd2 : 2'd0);

assign select_ln488_fu_276_p3 = ((tmp_4_fu_242_p3[0:0] === 1'b1) ? 8'd4 : 8'd0);

assign sub_ln248_1_fu_394_p2 = (trunc_ln612_fu_380_p1 - zext_ln488_1_fu_384_p1);

assign sub_ln248_fu_328_p2 = (p_Result_28_6_fu_308_p4 - zext_ln488_fu_318_p1);

assign sub_ln703_10_fu_1217_p2 = (select_ln339_5_fu_1210_p3 - zext_ln1494_5_fu_1181_p1);

assign sub_ln703_11_fu_1354_p2 = (select_ln318_16_reg_2986 - trunc_ln708_12_reg_2998);

assign sub_ln703_12_fu_1363_p2 = (select_ln339_6_fu_1358_p3 - zext_ln1494_6_reg_3003);

assign sub_ln703_13_fu_1493_p2 = (14'd0 - mul_FL_V_7_fu_1427_p3);

assign sub_ln703_14_fu_1531_p2 = (p_neg_7_fu_1523_p3 - trunc_ln708_14_fu_1420_p3);

assign sub_ln703_15_fu_1557_p2 = (select_ln339_7_fu_1549_p3 - zext_ln1494_7_fu_1435_p1);

assign sub_ln703_16_fu_1697_p2 = (select_ln318_22_fu_1612_p3 - mul_FL_V_8_fu_1645_p3);

assign sub_ln703_17_fu_1733_p2 = (p_neg_8_fu_1725_p3 - trunc_ln708_15_fu_1638_p3);

assign sub_ln703_18_fu_1901_p2 = (select_ln318_26_reg_3067 - mul_FL_V_9_reg_3097);

assign sub_ln703_19_fu_1926_p2 = (p_neg_9_reg_3108 - trunc_ln708_16_fu_1856_p4);

assign sub_ln703_1_fu_699_p2 = (select_ln318_1_fu_636_p3 - trunc_ln708_4_fu_668_p4);

assign sub_ln703_20_fu_2088_p2 = (select_ln318_30_fu_1982_p3 - mul_FL_V_s_fu_2032_p3);

assign sub_ln703_21_fu_2174_p2 = (p_neg_10_reg_3130 - trunc_ln708_17_reg_3125);

assign sub_ln703_22_fu_2286_p2 = (select_ln318_34_reg_3141 - mul_FL_V_1_fu_2233_p3);

assign sub_ln703_23_fu_2323_p2 = (p_neg_11_fu_2315_p3 - trunc_ln708_18_fu_2224_p4);

assign sub_ln703_24_fu_2481_p2 = (select_ln318_38_reg_3179 - mul_FL_V_2_fu_2428_p3);

assign sub_ln703_25_fu_2518_p2 = (p_neg_12_fu_2510_p3 - trunc_ln708_19_fu_2419_p4);

assign sub_ln703_2_fu_719_p2 = (select_ln339_1_fu_711_p3 - zext_ln1494_1_fu_677_p1);

assign sub_ln703_3_fu_824_p2 = (select_ln318_4_reg_2891 - trunc_ln708_6_fu_794_p4);

assign sub_ln703_4_fu_843_p2 = (select_ln339_2_fu_835_p3 - zext_ln1494_2_fu_803_p1);

assign sub_ln703_5_fu_965_p2 = (select_ln318_7_reg_2905 - trunc_ln708_8_reg_2917);

assign sub_ln703_6_fu_974_p2 = (select_ln339_3_fu_969_p3 - zext_ln1494_3_reg_2922);

assign sub_ln703_7_fu_1072_p2 = (select_ln318_10_fu_1010_p3 - trunc_ln708_s_fu_1041_p4);

assign sub_ln703_8_fu_1092_p2 = (select_ln339_4_fu_1084_p3 - zext_ln1494_4_fu_1050_p1);

assign sub_ln703_9_fu_1200_p2 = (select_ln318_13_reg_2958 - trunc_ln708_10_fu_1173_p4);

assign sub_ln703_fu_611_p2 = (select_ln339_fu_606_p3 - zext_ln1494_fu_586_p1);

always @ (*) begin
    tmp_10_fu_412_p4 = select_ln488_2_fu_356_p3;
    tmp_10_fu_412_p4[32'd0] = |(1'd1);
end

assign tmp_12_fu_438_p4 = {{x_V_int_reg[12:11]}};

assign tmp_14_fu_460_p4 = {{x_V_int_reg[12:11]}};

always @ (*) begin
    tmp_16_fu_757_p4 = select_ln318_reg_2869;
    tmp_16_fu_757_p4[32'd12] = |(1'd1);
end

always @ (*) begin
    tmp_18_fu_849_p4 = select_ln318_3_fu_766_p3;
    tmp_18_fu_849_p4[32'd11] = |(1'd1);
end

assign tmp_1_fu_2003_p4 = {{select_ln318_29_fu_1975_p3[9:3]}};

always @ (*) begin
    tmp_20_fu_979_p4 = select_ln318_6_reg_2899;
    tmp_20_fu_979_p4[32'd10] = |(1'd1);
end

always @ (*) begin
    tmp_21_fu_1098_p4 = select_ln318_9_fu_1003_p3;
    tmp_21_fu_1098_p4[32'd9] = |(1'd1);
end

assign tmp_22_fu_1410_p4 = {{select_ln318_18_fu_1377_p3[13:7]}};

always @ (*) begin
    tmp_23_fu_1223_p4 = select_ln318_12_reg_2952;
    tmp_23_fu_1223_p4[32'd8] = |(1'd1);
end

assign tmp_24_fu_1628_p4 = {{select_ln318_21_fu_1606_p3[13:8]}};

assign tmp_26_fu_2013_p4 = {{select_ln318_29_fu_1975_p3[13:10]}};

assign tmp_27_fu_2214_p4 = {{select_ln318_33_fu_2192_p3[13:11]}};

assign tmp_28_fu_2409_p4 = {{select_ln318_37_fu_2388_p3[13:12]}};

always @ (*) begin
    tmp_29_fu_1368_p4 = select_ln318_15_reg_2980;
    tmp_29_fu_1368_p4[32'd7] = |(1'd1);
end

assign tmp_2_fu_2204_p4 = {{select_ln318_33_fu_2192_p3[10:2]}};

assign tmp_30_fu_2740_p4 = {{res_FH_V_fu_2714_p2[13:1]}};

assign tmp_31_fu_1395_p3 = select_ln318_18_fu_1377_p3[32'd6];

always @ (*) begin
    tmp_33_fu_1597_p4 = select_ln318_18_reg_3025;
    tmp_33_fu_1597_p4[32'd6] = |(1'd1);
end

always @ (*) begin
    tmp_34_fu_1756_p4 = select_ln318_21_fu_1606_p3;
    tmp_34_fu_1756_p4[32'd5] = |(1'd1);
end

always @ (*) begin
    tmp_35_fu_1948_p4 = select_ln318_25_reg_3061;
    tmp_35_fu_1948_p4[32'd4] = |(1'd1);
end

always @ (*) begin
    tmp_36_fu_2183_p4 = select_ln318_29_reg_3113;
    tmp_36_fu_2183_p4[32'd3] = |(1'd1);
end

always @ (*) begin
    tmp_37_fu_2379_p4 = select_ln318_33_reg_3157;
    tmp_37_fu_2379_p4[32'd2] = |(1'd1);
end

always @ (*) begin
    tmp_38_fu_2542_p4 = select_ln318_37_fu_2388_p3;
    tmp_38_fu_2542_p4[32'd1] = |(1'd1);
end

assign tmp_3_fu_2399_p4 = {{select_ln318_37_fu_2388_p3[11:1]}};

always @ (*) begin
    tmp_40_fu_2671_p4 = select_ln318_41_reg_3195;
    tmp_40_fu_2671_p4[32'd0] = |(1'd1);
end

assign tmp_4_fu_242_p3 = x_V_int_reg[32'd17];

assign tmp_6_fu_300_p3 = {{select_ln488_6_fu_292_p3}, {1'd1}};

assign tmp_7_fu_372_p3 = {{select_ln488_2_fu_356_p3}, {1'd1}};

always @ (*) begin
    tmp_8_fu_346_p4 = select_ln488_fu_276_p3;
    tmp_8_fu_346_p4[32'd1] = |(1'd1);
end

assign tmp_9_fu_1618_p4 = {{select_ln318_21_fu_1606_p3[7:5]}};

assign tmp_fu_224_p4 = {{x_V_int_reg[17:13]}};

assign tmp_s_fu_1814_p4 = {{select_ln318_25_fu_1784_p3[8:4]}};

assign trunc_ln103_fu_2600_p1 = select_ln318_41_fu_2570_p3[12:0];

assign trunc_ln612_fu_380_p1 = select_ln488_3_fu_364_p3[9:0];

assign trunc_ln708_10_fu_1173_p4 = {{{trunc_ln708_24_reg_2844_pp0_iter3_reg}, {p_Result_34_5_reg_2975}}, {3'd4}};

assign trunc_ln708_11_fu_1286_p3 = {{14'd0}, {tmp_19_reg_2849_pp0_iter3_reg}};

assign trunc_ln708_12_fu_1293_p4 = {{{trunc_ln708_25_reg_2854_pp0_iter3_reg}, {p_Result_34_6_fu_1276_p4}}, {1'd1}};

assign trunc_ln708_13_fu_1403_p3 = {{15'd0}, {tmp_32_reg_2859_pp0_iter4_reg}};

assign trunc_ln708_14_fu_1420_p3 = {{trunc_ln708_26_reg_2864_pp0_iter4_reg}, {tmp_22_fu_1410_p4}};

assign trunc_ln708_15_fu_1638_p3 = {{select_ln488_4_reg_2763_pp0_iter5_reg}, {tmp_24_fu_1628_p4}};

assign trunc_ln708_16_fu_1856_p4 = {{{{1'd0}, {select_ln488_4_reg_2763_pp0_iter6_reg}}}, {tmp_25_reg_3092}};

assign trunc_ln708_17_fu_2023_p4 = {{{{2'd0}, {select_ln488_4_reg_2763_pp0_iter6_reg}}}, {tmp_26_fu_2013_p4}};

assign trunc_ln708_18_fu_2224_p4 = {{{{3'd0}, {select_ln488_4_reg_2763_pp0_iter7_reg}}}, {tmp_27_fu_2214_p4}};

assign trunc_ln708_19_fu_2419_p4 = {{{{4'd0}, {select_ln488_4_reg_2763_pp0_iter8_reg}}}, {tmp_28_fu_2409_p4}};

assign trunc_ln708_1_fu_579_p3 = {{8'd0}, {select_ln488_4_reg_2763}};

assign trunc_ln708_20_fu_2638_p4 = {{{{5'd0}, {select_ln488_4_reg_2763_pp0_iter9_reg}}}, {tmp_39_reg_3207}};

assign trunc_ln708_21_fu_500_p1 = select_ln488_4_fu_422_p3[1:0];

assign trunc_ln708_22_fu_514_p1 = select_ln488_4_fu_422_p3[2:0];

assign trunc_ln708_23_fu_528_p1 = select_ln488_4_fu_422_p3[3:0];

assign trunc_ln708_24_fu_542_p1 = select_ln488_4_fu_422_p3[4:0];

assign trunc_ln708_25_fu_556_p1 = select_ln488_4_fu_422_p3[5:0];

assign trunc_ln708_26_fu_568_p1 = select_ln488_4_fu_422_p3[6:0];

assign trunc_ln708_2_fu_1166_p3 = {{13'd0}, {tmp_17_reg_2839_pp0_iter3_reg}};

assign trunc_ln708_3_fu_661_p3 = {{9'd0}, {tmp_5_reg_2799}};

assign trunc_ln708_4_fu_668_p4 = {{{trunc_ln708_reg_2804}, {p_Result_34_1_fu_651_p4}}, {11'd1024}};

assign trunc_ln708_5_fu_787_p3 = {{10'd0}, {tmp_11_reg_2809_pp0_iter1_reg}};

assign trunc_ln708_6_fu_794_p4 = {{{trunc_ln708_21_reg_2814_pp0_iter1_reg}, {p_Result_34_2_fu_777_p4}}, {9'd256}};

assign trunc_ln708_7_fu_915_p3 = {{11'd0}, {tmp_13_reg_2819_pp0_iter1_reg}};

assign trunc_ln708_8_fu_922_p4 = {{{trunc_ln708_22_reg_2824_pp0_iter1_reg}, {p_Result_34_3_fu_905_p4}}, {7'd64}};

assign trunc_ln708_9_fu_1034_p3 = {{12'd0}, {tmp_15_reg_2829_pp0_iter2_reg}};

assign trunc_ln708_fu_486_p1 = select_ln488_4_fu_422_p3[0:0];

assign trunc_ln708_s_fu_1041_p4 = {{{trunc_ln708_23_reg_2834_pp0_iter2_reg}, {p_Result_34_4_fu_1024_p4}}, {5'd16}};

assign trunc_ln731_fu_238_p1 = x_V_int_reg[12:0];

assign x_l_FH_V_fu_572_p3 = {{trunc_ln731_reg_2758}, {1'd0}};

assign x_l_I_V_fu_234_p1 = tmp_fu_224_p4;

assign xor_ln248_fu_250_p2 = (tmp_4_fu_242_p3 ^ 1'd1);

assign xor_ln318_10_fu_1114_p2 = (icmp_ln318_4_fu_1108_p2 ^ 1'd1);

assign xor_ln318_11_fu_1237_p2 = (icmp_ln318_5_fu_1232_p2 ^ 1'd1);

assign xor_ln318_12_fu_1336_p2 = (icmp_ln318_6_fu_1330_p2 ^ 1'd1);

assign xor_ln318_1_fu_1766_p2 = (or_ln318_12_fu_1691_p2 ^ 1'd1);

assign xor_ln318_2_fu_1957_p2 = (or_ln318_16_fu_1895_p2 ^ 1'd1);

assign xor_ln318_3_fu_2140_p2 = (or_ln318_17_fu_2082_p2 ^ 1'd1);

assign xor_ln318_4_fu_2347_p2 = (or_ln318_18_fu_2280_p2 ^ 1'd1);

assign xor_ln318_5_fu_2552_p2 = (or_ln318_19_fu_2475_p2 ^ 1'd1);

assign xor_ln318_6_fu_2680_p2 = (or_ln318_20_fu_2665_p2 ^ 1'd1);

assign xor_ln318_7_fu_731_p2 = (icmp_ln318_1_fu_725_p2 ^ 1'd1);

assign xor_ln318_8_fu_864_p2 = (icmp_ln318_2_fu_859_p2 ^ 1'd1);

assign xor_ln318_9_fu_988_p2 = (icmp_ln318_3_reg_2947 ^ 1'd1);

assign xor_ln318_fu_1563_p2 = (or_ln318_8_fu_1487_p2 ^ 1'd1);

assign zext_ln1192_fu_2704_p1 = select_ln318_45_fu_2697_p3;

assign zext_ln1494_1_fu_677_p1 = trunc_ln708_3_fu_661_p3;

assign zext_ln1494_2_fu_803_p1 = trunc_ln708_5_fu_787_p3;

assign zext_ln1494_3_fu_931_p1 = trunc_ln708_7_fu_915_p3;

assign zext_ln1494_4_fu_1050_p1 = trunc_ln708_9_fu_1034_p3;

assign zext_ln1494_5_fu_1181_p1 = trunc_ln708_2_fu_1166_p3;

assign zext_ln1494_6_fu_1302_p1 = trunc_ln708_11_fu_1286_p3;

assign zext_ln1494_7_fu_1435_p1 = trunc_ln708_13_fu_1403_p3;

assign zext_ln1494_fu_586_p1 = trunc_ln708_1_fu_579_p3;

assign zext_ln488_1_fu_384_p1 = tmp_7_fu_372_p3;

assign zext_ln488_fu_318_p1 = tmp_6_fu_300_p3;

always @ (posedge ap_clk) begin
    select_ln318_reg_2869[12:0] <= 13'b0000000000000;
    select_ln318_4_reg_2891[0] <= 1'b0;
    select_ln318_7_reg_2905[0] <= 1'b0;
    trunc_ln708_8_reg_2917[6:0] <= 7'b1000000;
    zext_ln1494_3_reg_2922[17:5] <= 13'b0000000000000;
    select_ln318_13_reg_2958[0] <= 1'b0;
    select_ln318_16_reg_2986[0] <= 1'b0;
    trunc_ln708_12_reg_2998[0] <= 1'b1;
    zext_ln1494_6_reg_3003[17:2] <= 16'b0000000000000000;
    sub_ln703_13_reg_3031[12:0] <= 13'b1000000000000;
    select_ln318_26_reg_3067[9:0] <= 10'b0000000000;
    mul_FL_V_9_reg_3097[8:0] <= 9'b100000000;
    trunc_ln708_17_reg_3125[13:12] <= 2'b00;
    select_ln318_34_reg_3141[5:0] <= 6'b000000;
    select_ln318_38_reg_3179[3:0] <= 4'b0000;
end

endmodule //sqrt_fixed_28_15_s
